import Link from "next/link";
import { benefits, features } from "../model/content";
import { DashboardPreview } from "./dashboard-preview";
import { Icon, Logo } from "./icons";
import "./landing.css";

export function LandingPage() {
  return <main className="landing">
    <header className="site-header"><a href="#home" aria-label="Bagamanoc Water home"><Logo /></a><nav aria-label="Main navigation"><a href="#home">Home</a><a href="#features">Features</a><a href="#about">About</a><a href="#benefits">Benefits</a><a href="#contact">Contact</a></nav><Link href="/login" className="login-button"><Icon name="login" size={18}/> Log in</Link></header>
    <section className="hero" id="home"><div className="hero-glow"/><div className="hero-copy"><span className="eyebrow">Efficient. Accurate. Transparent.</span><h1>Smart Water Billing for a <em>Better Tomorrow</em></h1><p>A modern and reliable water billing system designed to simplify billing, improve collection efficiency, and provide excellent service to every customer.</p><div className="hero-actions"><Link href="/login" className="primary-button">Get started <Icon name="arrow" size={18}/></Link><a href="#features" className="secondary-button">Explore features</a></div><div className="benefit-strip" id="benefits">{benefits.map(item=><div key={item.title}><i><Icon name={item.icon}/></i><span><b>{item.title}</b><small>{item.copy}</small></span></div>)}</div></div><div className="hero-visual"><div className="water-orb one"/><div className="water-orb two"/><DashboardPreview /></div></section>
    <section className="features-section" id="features"><div className="section-heading"><span>FEATURES</span><h2>Everything you need in one system</h2><p>Purpose-built tools to help the water district manage billing and collections with clarity and efficiency.</p></div><div className="feature-grid">{features.map(item=><article key={item.title}><i><Icon name={item.icon} size={28}/></i><h3>{item.title}</h3><p>{item.copy}</p></article>)}</div></section>
    <section className="about-section" id="about"><div className="about-art"><div className="sun"/><div className="cloud cloud-one"/><div className="cloud cloud-two"/><div className="water-tank"><i/><span/></div><div className="drop"><Logo compact /></div><div className="meter-illustration"><div className="meter-face"><small>m³</small><b>001234<span>56</span></b></div></div><div className="ground"/></div><div className="about-copy"><span>BUILT FOR LOCAL SERVICE</span><h2>Better management.<br/>Stronger <em>communities.</em></h2><p>Bagamanoc Water Billing System helps the district streamline operations, increase collection efficiency, and deliver dependable service to every household.</p><div className="about-points"><div><Icon name="shield"/><span><b>Secure & reliable</b><small>Your information stays protected.</small></span></div><div><Icon name="clock"/><span><b>Accessible anywhere</b><small>Reach the system when work calls.</small></span></div><div><Icon name="heart"/><span><b>Customer focused</b><small>Designed around better service.</small></span></div></div></div></section>
    <section className="cta"><div><span>READY TO GET STARTED?</span><h2>Make every drop—and every peso—count.</h2></div><Link href="/login" className="light-button">Access the system <Icon name="arrow" size={18}/></Link></section>
    <footer id="contact"><div className="footer-brand"><Logo/><p>Modern water billing for efficient, accurate, and transparent public service.</p></div><div><h3>Quick links</h3><a href="#home">Home</a><a href="#features">Features</a><a href="#about">About</a><a href="#benefits">Benefits</a></div><div><h3>Resources</h3><Link href="/login">Staff login</Link><Link href="/register">User registration</Link><a href="#features">System overview</a></div><div className="contact-list"><h3>Contact us</h3><span><Icon name="phone" size={16}/> (052) 123-4567</span><span><Icon name="mail" size={16}/> info@bagamanocwater.gov.ph</span><span><Icon name="pin" size={16}/> Municipal Hall, Bagamanoc, Catanduanes</span></div><small className="copyright">© 2026 Bagamanoc Water Billing System. All rights reserved.</small></footer>
  </main>;
}
