"use client";

import Link from "next/link";
import { useCallback, useDeferredValue, useEffect, useState } from "react";
import type { CustomerListRow } from "@/modules/customers/types";
import { ModuleShell } from "@/modules/service-applications/ui/module-shell";
import styles from "@/modules/service-applications/ui/service-applications.module.css";
import { CustomerStatusBadge } from "./customer-status-badge";

type Summary={total:number;active:number;with_accounts:number;pending_applications:number}; type Pagination={page:number;pageSize:number;total:number;totalPages:number};
export function CustomersPage(){const[customers,setCustomers]=useState<CustomerListRow[]>([]);const[summary,setSummary]=useState<Summary>({total:0,active:0,with_accounts:0,pending_applications:0});const[pagination,setPagination]=useState<Pagination>({page:1,pageSize:10,total:0,totalPages:1});const[search,setSearch]=useState("");const deferredSearch=useDeferredValue(search);const[status,setStatus]=useState("");const[loading,setLoading]=useState(true);const[error,setError]=useState("");
const load=useCallback(async(page:number)=>{setLoading(true);setError("");const params=new URLSearchParams({page:String(page),pageSize:"10"});if(deferredSearch.trim())params.set("search",deferredSearch.trim());if(status)params.set("status",status);try{const response=await fetch(`/api/customers?${params}`,{cache:"no-store"});const body=await response.json();if(!response.ok)throw new Error(body.message);setCustomers(body.data);setSummary(body.summary);setPagination(body.pagination);}catch(loadError){setError(loadError instanceof Error?loadError.message:"Unable to load customer records.");}finally{setLoading(false);}},[deferredSearch,status]);useEffect(()=>{const timer=window.setTimeout(()=>void load(1),0);return()=>window.clearTimeout(timer);},[load]);const hasFilters=Boolean(search||status);const cards=[["Total Customers",summary.total],["Active Customers",summary.active],["With Service Accounts",summary.with_accounts],["With Pending Applications",summary.pending_applications]] as const;
return <ModuleShell active="customers"><div className={styles.headingRow}><div><div className={styles.eyebrow}>Customer Management</div><h1 className={styles.title}>Customers</h1><p className={styles.subtitle}>Manage customer records and their water service relationships.</p></div><Link className={styles.button} href="/transactions/customers/new">＋ Add Customer</Link></div><section className={styles.summaryGrid}>{cards.map(([label,value])=><article className={styles.summaryCard} key={label}><div className={styles.summaryLabel}>{label}</div><div className={styles.summaryValue}>{value.toLocaleString()}</div></article>)}</section><section className={styles.panel}><div className={styles.filters} style={{gridTemplateColumns:"minmax(280px,2fr) minmax(180px,1fr)"}}><div className={styles.searchWrap}><svg className={styles.searchIcon} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg><input className={styles.input} placeholder="Search customer..." value={search} onChange={(event)=>setSearch(event.target.value)}/></div><select className={styles.select} value={status} onChange={(event)=>setStatus(event.target.value)}><option value="">All Statuses</option><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option></select></div>
{loading?<div className={styles.tableWrap}><table className={styles.table}><thead><tr>{["Customer No.","Customer","Address","Contact","Applications","Service Accounts","Status","Actions"].map((heading)=><th key={heading}>{heading}</th>)}</tr></thead><tbody>{Array.from({length:6}).map((_,row)=><tr key={row}>{Array.from({length:8}).map((__,cell)=><td key={cell}><div className={styles.skeleton}/></td>)}</tr>)}</tbody></table></div>:error?<div className={styles.errorState}><h2>We couldn&apos;t load the customers</h2><p>{error}</p><button className={styles.secondaryButton} onClick={()=>load(pagination.page)}>Try again</button></div>:customers.length===0?<div className={styles.empty}><div className={styles.emptyIcon}>♙</div><h2>{hasFilters?"No customers match your search.":"No customers found."}</h2><p>{hasFilters?"Try clearing your search or status filter.":"Add a customer to begin creating service applications and service accounts."}</p>{hasFilters?<button className={styles.secondaryButton} onClick={()=>{setSearch("");setStatus("");}}>Clear filters</button>:<Link className={styles.button} href="/transactions/customers/new">＋ Add Customer</Link>}</div>:<><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Customer No.</th><th>Customer</th><th>Address</th><th>Contact</th><th>Applications</th><th>Service Accounts</th><th>Status</th><th>Actions</th></tr></thead><tbody>{customers.map((customer)=><tr key={customer.customerNo}><td className={styles.strong}>{customer.customerNo}</td><td className={styles.strong}>{customer.customerName}</td><td><div>{customer.address||"—"}</div>{customer.barangay&&<div className={styles.muted}>{customer.barangay}</div>}</td><td>{customer.contactNo||"—"}</td><td>{customer.applicationCount}</td><td>{customer.serviceAccountCount}</td><td><CustomerStatusBadge status={customer.status}/></td><td><Link className={styles.viewLink} href={`/transactions/customers/${encodeURIComponent(customer.customerNo)}`}>View</Link></td></tr>)}</tbody></table></div><div className={styles.pagination}><span>Showing {(pagination.page-1)*pagination.pageSize+1}–{Math.min(pagination.page*pagination.pageSize,pagination.total)} of {pagination.total}</span><div className={styles.paginationButtons}><button className={styles.ghostButton} disabled={pagination.page<=1} onClick={()=>load(pagination.page-1)}>Previous</button><span>Page {pagination.page} of {pagination.totalPages}</span><button className={styles.ghostButton} disabled={pagination.page>=pagination.totalPages} onClick={()=>load(pagination.page+1)}>Next</button></div></div></>}</section></ModuleShell>;}
