import { db } from "@/lib/db";
import { requireSessionUser } from "@/lib/server-session";
import { findSimilarCustomers, normalizeCustomerPayload, validateCustomer } from "@/modules/customers/server";

export const runtime="nodejs"; type Context={params:Promise<{customerNo:string}>};
export async function GET(_request:Request,context:Context){const auth=await requireSessionUser();if(auth.response)return auth.response;const customerNo=decodeURIComponent((await context.params).customerNo);try{const result=await db.query(`SELECT c.customer_no AS "customerNo",c.customer_name AS "customerName",c.first_name AS "firstName",c.middle_name AS "middleName",c.last_name AS "lastName",c.address,b.barangay_name AS barangay,b.barangay_code AS "barangayCode",p.purok_name AS purok,COALESCE(p.purok_code,p.purok_name) AS "purokCode",c.contact_no AS "contactNo",c.email,c.status,
COALESCE((SELECT json_agg(json_build_object('applicationNo',sa.application_no,'applicationType',at.application_type_name,'applicationDate',sa.application_date::text,'status',ast.status_name,'statusCode',ast.status_code) ORDER BY sa.application_date DESC,sa.application_id DESC) FROM service_applications sa JOIN mt_application_type at ON at.application_type_id=sa.application_type_id JOIN mt_application_status ast ON ast.application_status_id=sa.application_status_id WHERE sa.customer_id=c.customer_id),'[]'::json) AS applications,
COALESCE((SELECT json_agg(json_build_object('controlNo',acc.control_no,'classification',cc.classification_name,'connectionType',COALESCE(ct.connection_type_name,'Not set'),'status',COALESCE(cs.status_name,'Not set'),'statusCode',COALESCE(cs.status_code,'')) ORDER BY acc.created_at DESC,acc.service_account_id DESC) FROM service_accounts acc JOIN mt_customer_classification cc ON cc.classification_id=acc.classification_id LEFT JOIN mt_connection_type ct ON ct.connection_type_id=acc.connection_type_id LEFT JOIN mt_connection_status cs ON cs.connection_status_id=acc.connection_status_id WHERE acc.customer_id=c.customer_id),'[]'::json) AS "serviceAccounts"
FROM customers c LEFT JOIN mt_barangay b ON b.barangay_id=c.barangay_id LEFT JOIN mt_purok p ON p.purok_id=c.purok_id WHERE c.customer_no=$1 LIMIT 1`,[customerNo]);if(!result.rows[0])return Response.json({success:false,message:"This customer could not be found."},{status:404});return Response.json({success:true,data:result.rows[0]});}catch(error){console.error("Unable to load customer:",error);return Response.json({success:false,message:"Unable to load the customer record."},{status:500});}}

export async function PUT(request:Request,context:Context){const auth=await requireSessionUser();if(auth.response)return auth.response;const customerNo=decodeURIComponent((await context.params).customerNo);let body:Record<string,unknown>;try{body=await request.json();}catch{return Response.json({success:false,message:"Invalid request."},{status:400});}const payload=normalizeCustomerPayload(body);const errors=validateCustomer(payload);if(Object.keys(errors).length)return Response.json({success:false,message:"Check the required fields.",errors},{status:400});const client=await db.connect();try{await client.query("BEGIN");const current=await client.query<{customer_id:string}>("SELECT customer_id FROM customers WHERE customer_no=$1 FOR UPDATE",[customerNo]);if(!current.rows[0])throw new Error("NOT_FOUND");const similar=await findSimilarCustomers(client,payload,customerNo);if(similar.length&&!body.allowDuplicate){await client.query("ROLLBACK");return Response.json({success:false,code:"LIKELY_DUPLICATE",message:"A similar customer record already exists.",matches:similar},{status:409});}let barangayId:string|null=null,purokId:string|null=null;if(payload.barangayCode){const result=await client.query<{barangay_id:string}>("SELECT barangay_id FROM mt_barangay WHERE barangay_code=$1 AND is_active=TRUE",[payload.barangayCode]);if(!result.rows[0])throw new Error("INVALID_LOCATION");barangayId=result.rows[0].barangay_id;}if(payload.purokCode){const result=await client.query<{purok_id:string}>("SELECT p.purok_id FROM mt_purok p JOIN mt_barangay b ON b.barangay_id=p.barangay_id WHERE COALESCE(p.purok_code,p.purok_name)=$1 AND b.barangay_code=$2 AND p.is_active=TRUE",[payload.purokCode,payload.barangayCode]);if(!result.rows[0])throw new Error("INVALID_LOCATION");purokId=result.rows[0].purok_id;}await client.query(`UPDATE customers SET customer_name=$1,first_name=$2,middle_name=$3,last_name=$4,address=$5,barangay_id=$6,purok_id=$7,contact_no=$8,email=$9,status=$10,updated_by=$11,updated_at=NOW() WHERE customer_id=$12`,[payload.customerName,payload.firstName,payload.middleName,payload.lastName,payload.address,barangayId,purokId,payload.contactNo,payload.email,payload.status,auth.user.userId,current.rows[0].customer_id]);await client.query("COMMIT");return Response.json({success:true,message:`Customer ${customerNo} was updated successfully.`});}catch(error){await client.query("ROLLBACK");const code=error instanceof Error?error.message:"";if(code==="NOT_FOUND")return Response.json({success:false,message:"This customer could not be found."},{status:404});if(code==="INVALID_LOCATION")return Response.json({success:false,message:"The selected location is unavailable."},{status:400});console.error("Unable to update customer:",error);return Response.json({success:false,message:"Unable to save customer. Please try again."},{status:500});}finally{client.release();}}
