import { db } from "@/lib/db";
import { requireAnyPermission, requirePermission } from "@/lib/permissions";
import { recalculateBill } from "@/modules/bills/server";

export const runtime = "nodejs";
const fail = (message: string, status: number) => Response.json({ success: false, message }, { status });
const text = (value: unknown, maximum = 30) => typeof value === "string" ? value.trim().slice(0, maximum) : "";
const validAmount = (value: string) => /^\d+(\.\d{1,2})?$/.test(value) && Number(value) > 0;

function parse(body: Record<string, unknown>) { const value = { billId: text(body.billId), penaltyId: text(body.penaltyId), baseAmount: text(body.baseAmount) }; const errors: Record<string, string> = {}; if (!/^\d+$/.test(value.billId)) errors.billId = "Bill is required."; if (!/^\d+$/.test(value.penaltyId)) errors.penaltyId = "Penalty type is required."; if (!validAmount(value.baseAmount)) errors.baseAmount = "Enter a base amount greater than zero."; return { value, errors }; }

export async function GET(request: Request) {
  const params = new URL(request.url).searchParams;
  if (params.get("options") === "1") { const auth = await requireAnyPermission(["BILL_CREATE", "BILL_EDIT"]); if (auth.response) return auth.response; const billId = text(params.get("billId")); if (!/^\d+$/.test(billId)) return fail("Bill is required.", 400); try { const result = await db.query(`SELECT pr.penalty_id AS "penaltyId",pr.penalty_name AS "penaltyName",pr.rate::text,pr.maximum_penalty::text AS "maximumPenalty" FROM mt_penalty_rates pr JOIN bills b ON b.bill_id=$1 WHERE pr.is_active=TRUE AND pr.effective_date<=b.bill_date AND (pr.expiration_date IS NULL OR pr.expiration_date>=b.bill_date) ORDER BY pr.penalty_name`, [billId]); const base = await db.query(`SELECT (b.previous_balance+COALESCE((SELECT SUM(d.amount) FROM bill_details d WHERE d.bill_id=b.bill_id),0)+b.connection_fee_amount+COALESCE((SELECT SUM(a.amount) FROM bill_adjustments a WHERE a.bill_id=b.bill_id AND a.approved_at IS NOT NULL),0))::text AS "baseAmount" FROM bills b WHERE b.bill_id=$1`, [billId]); return Response.json({ success: true, data: { penaltyTypes: result.rows, baseAmount: base.rows[0]?.baseAmount || "0.00" } }); } catch (error) { console.error(error); return fail("Unable to load penalty options.", 500); } }
  const auth = await requirePermission("BILL_VIEW"); if (auth.response) return auth.response; const billId = text(params.get("billId")); try { const result = await db.query(`SELECT bp.bill_penalty_id AS "billPenaltyId",bp.bill_id AS "billId",b.bill_no AS "billNo",pr.penalty_id AS "penaltyId",pr.penalty_name AS "penaltyName",bp.base_amount::text AS "baseAmount",bp.rate::text,bp.amount::text FROM bill_penalties bp JOIN bills b ON b.bill_id=bp.bill_id JOIN mt_penalty_rates pr ON pr.penalty_id=bp.penalty_id ${/^\d+$/.test(billId) ? "WHERE bp.bill_id=$1" : ""} ORDER BY bp.bill_penalty_id`, /^\d+$/.test(billId) ? [billId] : []); return Response.json({ success: true, data: result.rows }); } catch (error) { console.error(error); return fail("Unable to load bill penalties.", 500); }
}

export async function POST(request: Request) { const auth = await requirePermission("BILL_CREATE"); if (auth.response) return auth.response; let body: Record<string, unknown>; try { body = await request.json(); } catch { return fail("Invalid request.", 400); } const { value, errors } = parse(body); if (Object.keys(errors).length) return Response.json({ success: false, message: "Invalid penalty data.", errors }, { status: 400 }); const client = await db.connect(); try { await client.query("BEGIN"); const result = await client.query(`INSERT INTO bill_penalties(bill_id,penalty_id,base_amount,rate,amount) SELECT b.bill_id,pr.penalty_id,$3,pr.rate,LEAST(($3::numeric*pr.rate/100),COALESCE(pr.maximum_penalty,($3::numeric*pr.rate/100))) FROM bills b JOIN mt_penalty_rates pr ON pr.penalty_id=$2 WHERE b.bill_id=$1 AND pr.is_active=TRUE AND pr.effective_date<=b.bill_date AND (pr.expiration_date IS NULL OR pr.expiration_date>=b.bill_date) RETURNING bill_penalty_id AS "billPenaltyId"`, [value.billId,value.penaltyId,value.baseAmount]); if (!result.rows[0]) { await client.query("ROLLBACK"); return fail("The selected bill or active penalty type was not found.", 400); } await recalculateBill(client,value.billId,auth.user.userId); await client.query("COMMIT"); return Response.json({ success: true, data: result.rows[0], message: "Penalty added and bill recalculated." }, { status: 201 }); } catch (error) { await client.query("ROLLBACK"); console.error(error); return fail("Unable to add bill penalty.", 500); } finally { client.release(); } }
