import { db } from "@/lib/db";
import { requirePermission } from "@/lib/permissions";
import type { PoolClient } from "pg";

export const runtime = "nodejs";
type Allocation = { billId: string; amount: string };
type Bill = { billId: string; billNo: string; billDate: string; dueDate: string | null; totalAmountDue: string; penaltyAmount: string; adjustmentAmount: string; amountPaid: string; outstanding: string };
const fail = (message: string, status: number) => Response.json({ success: false, message }, { status });
const id = (v: unknown) => typeof v === "string" && /^\d+$/.test(v.trim());
const amount = (v: unknown) => typeof v === "string" && /^\d+(\.\d{1,2})?$/.test(v.trim());
const text = (v: unknown, max = 4000) => typeof v === "string" ? v.trim().slice(0, max) : "";
const outstandingSql = `SELECT b.bill_id::text AS "billId",b.bill_no AS "billNo",b.bill_date::text AS "billDate",b.due_date::text AS "dueDate",b.total_amount_due::text AS "totalAmountDue",b.penalty_amount::text AS "penaltyAmount",b.adjustment_amount::text AS "adjustmentAmount",COALESCE((SELECT SUM(pa.amount_allocated) FROM payment_allocations pa JOIN payments p ON p.payment_id=pa.payment_id WHERE pa.bill_id=b.bill_id AND UPPER(p.status)='POSTED'),0)::text AS "amountPaid",(b.total_amount_due-COALESCE((SELECT SUM(pa.amount_allocated) FROM payment_allocations pa JOIN payments p ON p.payment_id=pa.payment_id WHERE pa.bill_id=b.bill_id AND UPPER(p.status)='POSTED'),0))::text AS outstanding FROM bills b WHERE b.service_account_id=$1 AND UPPER(b.status) NOT IN ('VOID','PAID') AND b.total_amount_due>COALESCE((SELECT SUM(pa.amount_allocated) FROM payment_allocations pa JOIN payments p ON p.payment_id=pa.payment_id WHERE pa.bill_id=b.bill_id AND UPPER(p.status)='POSTED'),0) ORDER BY b.due_date NULLS LAST,b.bill_date,b.bill_id`;
async function nextReceiptNo(client: PoolClient, userId: string) { const r = await client.query<{ series_id: string; prefix: string | null; current_number: string; padding_length: number }>(`SELECT series_id::text,prefix,current_number::text,padding_length FROM mt_document_series WHERE UPPER(document_type) IN ('PAYMENT','RECEIPT') AND is_active=TRUE ORDER BY CASE UPPER(document_type) WHEN 'PAYMENT' THEN 0 ELSE 1 END,series_id FOR UPDATE LIMIT 1`); const s = r.rows[0]; if (!s) throw new Error("PAYMENT_SERIES_NOT_CONFIGURED"); const next = BigInt(s.current_number) + BigInt(1); await client.query("UPDATE mt_document_series SET current_number=$1,updated_by=$2,updated_at=NOW() WHERE series_id=$3", [next.toString(), userId, s.series_id]); return `${s.prefix || "OR-"}${next.toString().padStart(s.padding_length || 5, "0")}`; }

export async function GET(request: Request) {
  const auth = await requirePermission("BILL_EDIT"); if (auth.response) return auth.response;
  const q = new URL(request.url).searchParams, customerId = q.get("customerId")?.trim(), serviceAccountId = q.get("serviceAccountId")?.trim(); if ((customerId && !id(customerId)) || (serviceAccountId && !id(serviceAccountId))) return fail("Invalid payment lookup.", 400);
  try { const [paymentTypes, paymentMethods, receiptTypes, serviceAccounts, outstandingBills] = await Promise.all([
    db.query(`SELECT payment_type_id::text AS "paymentTypeId",payment_type_name AS name FROM mt_payment_type WHERE is_active=TRUE ORDER BY payment_type_code`), db.query(`SELECT payment_method_id::text AS "paymentMethodId",payment_method_name AS name FROM mt_payment_method WHERE is_active=TRUE ORDER BY payment_method_code`), db.query(`SELECT receipt_type_id::text AS "receiptTypeId",receipt_type_name AS name FROM mt_receipt_type WHERE is_active=TRUE ORDER BY receipt_type_code`),
    customerId || serviceAccountId ? db.query(`SELECT sa.service_account_id::text AS "serviceAccountId",sa.customer_id::text AS "customerId",sa.control_no AS "controlNo",c.customer_name AS "customerName",sa.address,COALESCE(cs.status_name,cs.status_code,'Not set') AS status,COALESCE(m.meter_no,'—') AS "meterNo",COALESCE(rr.route_code,'—') AS "routeCode" FROM service_accounts sa JOIN customers c ON c.customer_id=sa.customer_id LEFT JOIN mt_connection_status cs ON cs.connection_status_id=sa.connection_status_id LEFT JOIN mt_reading_route rr ON rr.route_id=sa.route_id LEFT JOIN LATERAL (SELECT meter_no FROM meters WHERE service_account_id=sa.service_account_id AND UPPER(status)='ACTIVE' ORDER BY meter_id DESC LIMIT 1) m ON TRUE WHERE ${serviceAccountId ? "sa.service_account_id=$1" : "sa.customer_id=$1"} ORDER BY sa.control_no`, [serviceAccountId || customerId]) : Promise.resolve({ rows: [] }), serviceAccountId ? db.query<Bill>(outstandingSql, [serviceAccountId]) : Promise.resolve({ rows: [] as Bill[] })]);
    return Response.json({ success: true, data: { paymentTypes: paymentTypes.rows, paymentMethods: paymentMethods.rows, receiptTypes: receiptTypes.rows, serviceAccounts: serviceAccounts.rows, outstandingBills: outstandingBills.rows } });
  } catch (error) { console.error("Unable to load payment information:", error); return fail("Unable to load payment information.", 500); }
}

export async function POST(request: Request) {
  const auth = await requirePermission("BILL_EDIT"); if (auth.response) return auth.response; let body: Record<string, unknown>; try { body = await request.json(); } catch { return fail("Invalid request.", 400); }
  const serviceAccountId = text(body.serviceAccountId, 30), paymentTypeId = text(body.paymentTypeId, 30), paymentMethodId = text(body.paymentMethodId, 30), receiptTypeId = text(body.receiptTypeId, 30) || null, paymentAmount = text(body.amount, 30), paymentDate = text(body.paymentDate, 10), referenceNo = text(body.referenceNo, 100) || null, remarks = text(body.remarks) || null, allocationMethod = text(body.allocationMethod, 10).toUpperCase() || "AUTO";
  const requested = Array.isArray(body.allocations) ? body.allocations.map((e): Allocation => ({ billId: text((e as Record<string, unknown>).billId, 30), amount: text((e as Record<string, unknown>).amount, 30) })).filter((e) => id(e.billId) && amount(e.amount) && Number(e.amount) > 0) : [];
  if (!id(serviceAccountId) || !id(paymentTypeId) || !id(paymentMethodId) || (receiptTypeId && !id(receiptTypeId)) || !amount(paymentAmount) || Number(paymentAmount) <= 0 || !/^\d{4}-\d{2}-\d{2}$/.test(paymentDate) || !["AUTO", "MANUAL"].includes(allocationMethod)) return fail("Complete the payment information with valid values.", 400);
  if (allocationMethod === "MANUAL" && (!requested.length || new Set(requested.map((e) => e.billId)).size !== requested.length)) return fail("Manual allocations must contain unique, positive bill amounts.", 400);
  const client = await db.connect(); try { await client.query("BEGIN");
    const account = await client.query<{ customerName: string; controlNo: string }>(`SELECT c.customer_name AS "customerName",sa.control_no AS "controlNo" FROM service_accounts sa JOIN customers c ON c.customer_id=sa.customer_id WHERE sa.service_account_id=$1 FOR UPDATE`, [serviceAccountId]); if (!account.rows[0]) throw new Error("INVALID_ACCOUNT");
    const masters = await Promise.all([client.query<{ name: string }>("SELECT payment_type_name AS name FROM mt_payment_type WHERE payment_type_id=$1 AND is_active=TRUE", [paymentTypeId]), client.query<{ name: string }>("SELECT payment_method_name AS name FROM mt_payment_method WHERE payment_method_id=$1 AND is_active=TRUE", [paymentMethodId]), receiptTypeId ? client.query<{ name: string }>("SELECT receipt_type_name AS name FROM mt_receipt_type WHERE receipt_type_id=$1 AND is_active=TRUE", [receiptTypeId]) : Promise.resolve({ rows: [{ name: "" }] })]); if (masters.some((r) => !r.rows[0])) throw new Error("INVALID_PAYMENT_OPTION");
    const bills = await client.query<Bill>(`${outstandingSql.replace("ORDER BY b.due_date NULLS LAST,b.bill_date,b.bill_id", "")} FOR UPDATE`, [serviceAccountId]); const byId = new Map(bills.rows.map((b) => [b.billId, b])); let allocations: Allocation[];
    if (allocationMethod === "AUTO") { let remaining = Number(paymentAmount); allocations = []; for (const bill of bills.rows) { const value = Math.min(remaining, Number(bill.outstanding)); if (value > 0) allocations.push({ billId: bill.billId, amount: value.toFixed(2) }); remaining -= value; if (remaining <= 0) break; } } else { allocations = requested; for (const a of allocations) { const bill = byId.get(a.billId); if (!bill) throw new Error("INVALID_BILL"); if (Number(a.amount) > Number(bill.outstanding) + .00001) throw new Error("OVER_ALLOCATION"); } }
    const totalAllocated = allocations.reduce((sum, a) => sum + Number(a.amount), 0); if (!allocations.length) throw new Error("NO_OUTSTANDING_BILLS"); if (Math.abs(totalAllocated - Number(paymentAmount)) > .00001) throw new Error("ALLOCATION_MISMATCH");
    const receiptNo = await nextReceiptNo(client, auth.user.userId); const payment = await client.query<{ paymentId: string }>(`INSERT INTO payments(receipt_no,service_account_id,payment_date,payment_type_id,payment_method_id,receipt_type_id,amount,cashier_id,status,reference_no,remarks,created_by) VALUES($1,$2,$3::date,$4,$5,$6,$7,$8,'POSTED',$9,$10,$8) RETURNING payment_id::text AS "paymentId"`, [receiptNo, serviceAccountId, paymentDate, paymentTypeId, paymentMethodId, receiptTypeId, paymentAmount, auth.user.userId, referenceNo, remarks]); const saved: Record<string, string>[] = [];
    for (const a of allocations) { const bill = byId.get(a.billId)!; await client.query("INSERT INTO payment_allocations(payment_id,bill_id,amount_allocated) VALUES($1,$2,$3)", [payment.rows[0].paymentId, a.billId, a.amount]); const updated = await client.query<{ status: string }>(`UPDATE bills SET status=CASE WHEN total_amount_due<=COALESCE((SELECT SUM(pa.amount_allocated) FROM payment_allocations pa JOIN payments p ON p.payment_id=pa.payment_id WHERE pa.bill_id=bills.bill_id AND UPPER(p.status)='POSTED'),0) THEN 'PAID' ELSE 'PARTIAL' END,updated_by=$1,updated_at=NOW() WHERE bill_id=$2 RETURNING status`, [auth.user.userId, a.billId]); saved.push({ billNo: bill.billNo, billDate: bill.billDate, penaltyAmount: bill.penaltyAmount, adjustmentAmount: bill.adjustmentAmount, amount: a.amount, resultingStatus: updated.rows[0].status }); }
    await client.query("COMMIT"); return Response.json({ success: true, data: { paymentId: payment.rows[0].paymentId, receiptNo, customerName: account.rows[0].customerName, controlNo: account.rows[0].controlNo, paymentDate, paymentAmount, paymentType: masters[0].rows[0].name, paymentMethod: masters[1].rows[0].name, receiptType: masters[2].rows[0].name, referenceNo, totalAllocated: totalAllocated.toFixed(2), remaining: "0.00", allocationMethod, allocations: saved }, message: "Payment and allocations saved successfully." }, { status: 201 });
  } catch (error) { await client.query("ROLLBACK"); const code = error instanceof Error ? error.message : ""; const messages: Record<string, [string, number]> = { INVALID_ACCOUNT: ["The selected service account was not found.", 404], INVALID_PAYMENT_OPTION: ["A selected payment option is unavailable.", 400], INVALID_BILL: ["A manual allocation includes a bill that is not outstanding for this account.", 409], OVER_ALLOCATION: ["An allocation exceeds the bill's remaining balance.", 409], NO_OUTSTANDING_BILLS: ["This service account has no outstanding bills.", 409], ALLOCATION_MISMATCH: ["The payment must be fully allocated to outstanding bills.", 409], PAYMENT_SERIES_NOT_CONFIGURED: ["An active PAYMENT or RECEIPT document series must be configured before payments can be saved.", 409] }; if (messages[code]) return fail(...messages[code]); console.error("Unable to save payment:", error); return fail("Unable to save payment.", 500); } finally { client.release(); }
}
