import { db } from "@/lib/db";
import { requirePermission } from "@/lib/permissions";

export const runtime = "nodejs";
const text = (value: string | null, maximum = 100) => (value || "").trim().slice(0, maximum);
const fail = (message: string, status: number) => Response.json({ success: false, message }, { status });

export async function GET(request: Request) {
  const auth = await requirePermission("METER_READING_VIEW"); if (auth.response) return auth.response;
  const params = new URL(request.url).searchParams, search = text(params.get("search")), route = text(params.get("route"), 30), period = text(params.get("billingPeriod"), 30), status = text(params.get("status"), 30), reader = text(params.get("reader"), 30), values: unknown[] = [], where: string[] = [];
  for (const [value, clause, fuzzy] of [[search, "(sa.control_no ILIKE $ OR c.customer_name ILIKE $ OR m.meter_no ILIKE $)", true], [route, "rr.route_id::text=$", false], [period, "bp.billing_period_id::text=$", false], [status, "rs.reading_status_id::text=$", false], [reader, "mr.meter_reader_id::text=$", false]] as const) if (value) { values.push(fuzzy ? `%${value}%` : value); where.push(clause.replaceAll("$", `$${values.length}`)); }
  try { const result = await db.query(`SELECT rd.reading_id AS "readingId",rd.service_account_id AS "serviceAccountId",rd.meter_id AS "meterId",rd.billing_period_id AS "billingPeriodId",rd.reading_date::text AS "readingDate",rd.previous_reading::text AS "previousReading",rd.present_reading::text AS "presentReading",rd.consumption::text AS consumption,sa.control_no AS "controlNo",c.customer_name AS "customerName",m.meter_no AS "meterNo",COALESCE(bp.period_name,bp.period_code) AS "billingPeriod",rr.route_code AS "routeCode",rr.route_name AS "routeName",rs.status_name AS "readingStatus",e.employee_name AS "meterReader" FROM meter_readings rd JOIN service_accounts sa ON sa.service_account_id=rd.service_account_id JOIN customers c ON c.customer_id=sa.customer_id JOIN meters m ON m.meter_id=rd.meter_id JOIN mt_billing_period bp ON bp.billing_period_id=rd.billing_period_id LEFT JOIN mt_reading_route rr ON rr.route_id=sa.route_id LEFT JOIN mt_reading_status rs ON rs.reading_status_id=rd.reading_status_id LEFT JOIN mt_meter_reader mr ON mr.meter_reader_id=rd.meter_reader_id LEFT JOIN mt_employee e ON e.employee_id=mr.employee_id ${where.length ? `WHERE ${where.join(" AND ")}` : ""} ORDER BY rd.reading_date DESC,rd.reading_id DESC`, values); return Response.json({ success: true, data: result.rows }); } catch (error) { console.error("Unable to load meter readings:", error); return fail("Unable to load meter readings.", 500); }
}
