"use client";
/* eslint-disable @next/next/no-img-element */

import { useCallback, useEffect, useMemo, useState } from "react";
import { TransactionShell } from "@/modules/transactions/ui/transaction-shell";
import styles from "@/modules/transactions/ui/transactions.module.css";

type Option = { billingPeriodId?: string; meterReaderId?: string; routeId?: string; periodCode?: string; periodName?: string; employeeCode?: string; employeeName?: string; routeCode?: string; routeName?: string };
type Photo = { readingPhotoId: string; photoType: string; fileName: string; capturedAt: string | null; latitude: string | null; longitude: string | null; uploadedAt: string };
type Reading = Record<string, string | number | boolean | null | Photo[]> & { photos?: Photo[] };
type Summary = { assigned: number; inProgress: number; returned: number; validated: number; forReview: number };
const value = (row: Reading, key: string) => row[key] == null ? "—" : String(row[key]);
const number = (row: Reading, key: string) => row[key] == null ? "—" : Number(row[key]).toLocaleString("en-PH", { maximumFractionDigits: 3 });
const timestamp = (value: string | null | undefined) => {
  if (!value) return "—";
  try {
    let normalized = value.trim().replace(" ", "T");
    normalized = normalized.replace(/(\.\d{3})\d+/, "$1");
    const date = new Date(normalized);
    if (Number.isNaN(date.getTime())) return "—";
    return new Intl.DateTimeFormat("en-PH", { dateStyle: "medium", timeStyle: "short" }).format(date);
  } catch {
    return "—";
  }
};
const photoUrl = (photo: Photo) => `/api/mobile/meter-readings/photos/${encodeURIComponent(photo.readingPhotoId)}`;
function badge(status: string) { const label = status === "COMPLETED" ? "For Review" : status === "VALIDATED" ? "Validated" : status === "IN_PROGRESS" ? "In Progress" : "For Read"; return <span className={`${styles.badge} ${status === "VALIDATED" ? styles.approved : status === "COMPLETED" ? styles.pending : styles.processing}`}>{label}</span>; }
async function load<T>(url: string) { const response = await fetch(url, { cache: "no-store" }); const body = await response.json(); if (!response.ok) throw new Error(body.message || "Unable to load mobile reading returns."); return body.data as T; }

function PhotoCard({ photo, readingId, onView, failed, onFailed }: { photo: Photo; readingId: string; onView: () => void; failed: boolean; onFailed: () => void }) {
  return <div className={styles.meterPhotoCard}>{failed ? <p className={styles.notice}>Photo record exists, but the image could not be loaded.</p> : <img className={styles.meterPhotoPreview} src={photoUrl(photo)} alt={`Meter photo for reading ${readingId}`} onError={onFailed} />}<div className={styles.photoMetadata}><div><span>File</span><strong>{photo.fileName}</strong></div><div><span>Captured</span><strong>{timestamp(photo.capturedAt)}</strong></div><div><span>Photo GPS</span><strong>{photo.latitude && photo.longitude ? `${photo.latitude}, ${photo.longitude}` : "Not captured"}</strong></div><div><span>Uploaded</span><strong>{timestamp(photo.uploadedAt)}</strong></div></div><button type="button" className={styles.secondaryButton} onClick={onView}>View Full Photo</button></div>;
}

export function MobileReturnsPage() {
  const [periods, setPeriods] = useState<Option[]>([]), [readers, setReaders] = useState<Option[]>([]), [routes, setRoutes] = useState<Option[]>([]), [rows, setRows] = useState<Reading[]>([]), [summary, setSummary] = useState<Summary>({ assigned: 0, inProgress: 0, returned: 0, validated: 0, forReview: 0 });
  const [filter, setFilter] = useState({ billingPeriodId: "", meterReaderId: "", routeId: "", batchId: "", readingStatusId: "", workflowStatus: "", search: "" }), [loading, setLoading] = useState(true), [error, setError] = useState(""), [detail, setDetail] = useState<Reading | null>(null), [fullPhoto, setFullPhoto] = useState<Photo | null>(null), [failedPhotos, setFailedPhotos] = useState<Set<string>>(new Set());
  const fetchReturns = useCallback(async () => { setLoading(true); try { const params = new URLSearchParams(Object.entries(filter).filter(([, item]) => item)); const data = await load<{ rows: Reading[]; summary: Summary }>(`/api/mobile/meter-readings/returns?${params}`); setRows(data.rows); setSummary(data.summary); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to load mobile reading returns."); } finally { setLoading(false); } }, [filter]);
  useEffect(() => { void (async () => { await Promise.resolve(); await fetchReturns(); })(); }, [fetchReturns]);
  useEffect(() => { void (async () => { try { const data = await load<{ periods: Option[]; meterReaders: Option[] }>("/api/mobile/meter-readings/transfer-options"); setPeriods(data.periods); setReaders(data.meterReaders); } catch { /* Filters remain usable without labels. */ } })(); }, []);
  useEffect(() => { if (!filter.billingPeriodId || !filter.meterReaderId) return; void (async () => { try { const data = await load<{ routes: Option[] }>(`/api/mobile/meter-readings/transfer-options?billingPeriodId=${filter.billingPeriodId}&meterReaderId=${filter.meterReaderId}`); setRoutes(data.routes); } catch { setRoutes([]); } })(); }, [filter.billingPeriodId, filter.meterReaderId]);
  const batches = useMemo(() => [...new Set(rows.map((row) => value(row, "batchId")).filter((batch) => batch !== "—"))], [rows]);
  const update = (key: keyof typeof filter, next: string) => setFilter((current) => ({ ...current, [key]: next, ...(key === "billingPeriodId" ? { meterReaderId: "", routeId: "", batchId: "" } : key === "meterReaderId" ? { routeId: "", batchId: "" } : {}) }));
  const markFailed = (photo: Photo) => setFailedPhotos((current) => new Set(current).add(photo.readingPhotoId));
  const controls = <section className={styles.panel}><div className={styles.filters} style={{ gridTemplateColumns: "repeat(4,minmax(150px,1fr))" }}><select className={styles.select} value={filter.billingPeriodId} onChange={(event) => update("billingPeriodId", event.target.value)}><option value="">All billing periods</option>{periods.map((item) => <option key={item.billingPeriodId} value={item.billingPeriodId}>{item.periodCode} — {item.periodName}</option>)}</select><select className={styles.select} value={filter.meterReaderId} onChange={(event) => update("meterReaderId", event.target.value)}><option value="">All meter readers</option>{readers.map((item) => <option key={item.meterReaderId} value={item.meterReaderId}>{item.employeeCode} — {item.employeeName}</option>)}</select><select className={styles.select} value={filter.routeId} disabled={!filter.meterReaderId} onChange={(event) => update("routeId", event.target.value)}><option value="">All assigned routes</option>{routes.map((item) => <option key={item.routeId} value={item.routeId}>{item.routeCode} — {item.routeName}</option>)}</select><select className={styles.select} value={filter.batchId} onChange={(event) => update("batchId", event.target.value)}><option value="">All batches</option>{batches.map((batch) => <option key={batch} value={batch}>Batch #{batch}</option>)}</select><select className={styles.select} value={filter.readingStatusId} onChange={(event) => update("readingStatusId", event.target.value)}><option value="">All conditions</option><option value="1">NORMAL</option><option value="2">ESTIMATED</option><option value="3">ZERO</option><option value="4">DEFECTIVE</option><option value="5">NO-READ</option></select><select className={styles.select} value={filter.workflowStatus} onChange={(event) => update("workflowStatus", event.target.value)}><option value="">All workflow states</option><option value="IN_PROGRESS">In Progress</option><option value="COMPLETED">For Review</option><option value="VALIDATED">Validated</option></select><input className={styles.input} value={filter.search} onChange={(event) => update("search", event.target.value)} placeholder="Control no., customer, or meter" /></div></section>;
  return <TransactionShell active="meter-readings"><div className={styles.headingRow}><div><div className={styles.eyebrow}>Meter Reading Operations</div><h1 className={styles.title}>Mobile Reading Returns</h1><p className={styles.subtitle}>Monitor readings returned from Android, review exceptions, and inspect captured mobile evidence.</p></div><button type="button" className={styles.secondaryButton} onClick={() => void fetchReturns()}>Refresh</button></div>{error && <div className={styles.notice}>{error}</div>}{controls}
    <div className={styles.summaryGrid} style={{ marginTop: 18 }}>{[["Assigned", summary.assigned], ["In Progress", summary.inProgress], ["Returned", summary.returned], ["Validated", summary.validated], ["For Review", summary.forReview]].map(([label, count]) => <div className={styles.summaryCard} key={String(label)}><div className={styles.summaryLabel}>{label}</div><div className={styles.summaryValue}>{count}</div></div>)}</div>
    <section className={styles.panel}><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Control No.</th><th>Customer</th><th>Address</th><th>Meter</th><th>Previous</th><th>Present</th><th>Consumption</th><th>Condition</th><th>Reader</th><th>Route</th><th>Batch</th><th>Workflow</th><th>Captured</th><th>Received</th><th>Evidence</th><th>Actions</th></tr></thead><tbody>{rows.map((row) => <tr key={value(row, "readingId")}><td>{value(row, "controlNo")}</td><td className={styles.strong}>{value(row, "customerName")}</td><td>{value(row, "serviceAddress")}</td><td>{value(row, "meterNo")}</td><td>{number(row, "previousReading")}</td><td>{number(row, "presentReading")}</td><td>{number(row, "consumption")}</td><td>{badge(value(row, "readingStatusCode"))}</td><td>{value(row, "meterReaderName")}</td><td>{value(row, "routeCode")}</td><td>{value(row, "batchId") === "—" ? "—" : `#${value(row, "batchId")}`}</td><td>{badge(value(row, "workflowStatusCode"))}</td><td>{timestamp(value(row, "readingCapturedAt"))}</td><td>{timestamp(value(row, "receivedAt"))}</td><td>{row.latitude && row.longitude ? "GPS captured" : "No GPS"}{row.hasPhoto ? " · Photo Available" : ""}</td><td><button type="button" className={styles.secondaryButton} onClick={() => setDetail(row)}>View Reading</button></td></tr>)}</tbody></table></div>{!loading && !rows.length && <div className={styles.empty}><h2>No mobile readings have been returned for the selected filters.</h2></div>}</section>
    {detail && <div className={styles.dialogBackdrop} role="presentation"><div className={`${styles.dialog} ${styles.accountBrowseDialog}`} role="dialog" aria-modal="true" aria-label="Mobile reading return"><div className={styles.dialogHeader}><div><h2>Reading #{value(detail, "readingId")}</h2><p>Read-only mobile return details.</p></div><button type="button" className={styles.dialogClose} onClick={() => setDetail(null)} aria-label="Close">×</button></div><div className={styles.detailItems} style={{ marginTop: 18 }}>{[["Control No.", "controlNo"], ["Customer", "customerName"], ["Service Address", "serviceAddress"], ["Meter No.", "meterNo"], ["Billing Period", "billingPeriodName"], ["Route", "routeName"], ["Previous", "previousReading"], ["Present", "presentReading"], ["Consumption", "consumption"], ["Condition", "readingStatusName"], ["Workflow", "workflowStatusCode"], ["Reading Date", "readingDate"], ["Remarks", "remarks"], ["Meter Reader", "meterReaderName"], ["Reader Code", "meterReaderCode"], ["Captured At", "readingCapturedAt"], ["Server Received At", "receivedAt"], ["Device ID", "deviceId"], ["Latitude", "latitude"], ["Longitude", "longitude"], ["GPS Accuracy", "gpsAccuracy"], ["Validated By", "validatedByUsername"], ["Validated At", "validatedAt"]].map(([label, key]) => <div className={styles.detailItem} key={key}><span>{label}</span><strong>{value(detail, key)}</strong></div>)}</div><section className={styles.meterPhotoSection}><h3>Meter Photo</h3>{detail.photos?.length ? detail.photos.map((photo) => <PhotoCard key={photo.readingPhotoId} photo={photo} readingId={value(detail, "readingId")} failed={failedPhotos.has(photo.readingPhotoId)} onFailed={() => markFailed(photo)} onView={() => setFullPhoto(photo)} />) : <p>No photo uploaded</p>}</section><div className={styles.dialogActions}><button type="button" className={styles.secondaryButton} onClick={() => setDetail(null)}>Close</button></div></div></div>}
    {fullPhoto && <div className={styles.dialogBackdrop} role="presentation"><div className={`${styles.dialog} ${styles.fullPhotoDialog}`} role="dialog" aria-modal="true" aria-label="Full meter photo"><div className={styles.dialogHeader}><div><h2>Meter Photo</h2><p>{fullPhoto.fileName}</p></div><button type="button" className={styles.dialogClose} onClick={() => setFullPhoto(null)} aria-label="Close">×</button></div>{failedPhotos.has(fullPhoto.readingPhotoId) ? <p className={styles.notice}>Photo record exists, but the image could not be loaded.</p> : <img className={styles.fullMeterPhoto} src={photoUrl(fullPhoto)} alt="Full meter photo" onError={() => markFailed(fullPhoto)} />}<p className={styles.photoFullMetadata}>Captured: {timestamp(fullPhoto.capturedAt)} · GPS: {fullPhoto.latitude && fullPhoto.longitude ? `${fullPhoto.latitude}, ${fullPhoto.longitude}` : "Not captured"}</p><div className={styles.dialogActions}><button type="button" className={styles.secondaryButton} onClick={() => setFullPhoto(null)}>Close</button></div></div></div>}
  </TransactionShell>;
}
