"use client";
/* eslint-disable react-hooks/set-state-in-effect, react-hooks/static-components */
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { TransactionShell } from "@/modules/transactions/ui/transaction-shell";
import styles from "@/modules/transactions/ui/transactions.module.css";

type Detail = { billDetailId: string; billId: string; billNo: string; controlNo: string; customerName: string; billingPeriod: string; chargeType: string; description: string | null; quantity: string; rate: string; amount: string; sequenceNo: number | null; createdAt: string; billDate?: string; billStatus?: string; rateId?: string | null; minimumCubicMeter?: string | null; maximumCubicMeter?: string | null; rateType?: string | null; effectiveDate?: string | null; expirationDate?: string | null };
const money = (value: string | null | undefined) => Number(value || 0).toLocaleString("en-PH", { style: "currency", currency: "PHP" });
const date = (value: string | null | undefined) => value ? new Intl.DateTimeFormat("en-PH", { dateStyle: "medium", timeZone: "UTC" }).format(new Date(`${value.slice(0, 10)}T00:00:00Z`)) : "—";
function useData<T>(url: string) { const [data, setData] = useState<T | null>(null), [error, setError] = useState(""), [loading, setLoading] = useState(true); const load = useCallback(async () => { setLoading(true); try { const response = await fetch(url, { cache: "no-store" }), body = await response.json(); if (!response.ok) throw new Error(body.message); setData(body.data); setError(""); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load bill details."); } finally { setLoading(false); } }, [url]); useEffect(() => { void load(); }, [load]); return { data, error, loading, load }; }
export function BillDetailsPage() { const [search, setSearch] = useState(""), [chargeType, setChargeType] = useState(""); const query = useMemo(() => { const p = new URLSearchParams(); if (search) p.set("search", search); if (chargeType) p.set("chargeType", chargeType); return p; }, [search, chargeType]); const { data, error, loading, load } = useData<Detail[]>(`/api/bill-details?${query}`); return <TransactionShell><div className={styles.headingRow}><div><div className={styles.eyebrow}>Billing Operations</div><h1 className={styles.title}>Bill Details</h1><p className={styles.subtitle}>Review the charge lines that explain each bill calculation.</p></div><Link className={styles.secondaryButton} href="/transactions">Bills</Link></div><section className={styles.panel}><div className={styles.filters}><input className={styles.input} value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Bill no., control no., or customer..." /><input className={styles.input} value={chargeType} onChange={(e) => setChargeType(e.target.value)} placeholder="Charge type" /></div>{loading ? <Loading /> : error ? <Failure message={error} retry={load} /> : !data?.length ? <div className={styles.empty}><h2>No bill details found.</h2></div> : <div className={styles.tableWrap}><table className={styles.table}><thead><tr>{["Bill No.", "Control No.", "Customer", "Billing Period", "Charge Type", "Description", "Quantity", "Rate", "Amount", "Sequence", "Created At", "Actions"].map((x) => <th key={x}>{x}</th>)}</tr></thead><tbody>{data.map((item) => <tr key={item.billDetailId}><td>{item.billNo}</td><td>{item.controlNo}</td><td>{item.customerName}</td><td>{item.billingPeriod}</td><td>{item.chargeType}</td><td>{item.description || "—"}</td><td>{item.quantity}</td><td>{money(item.rate)}</td><td className={styles.strong}>{money(item.amount)}</td><td>{item.sequenceNo ?? "—"}</td><td>{date(item.createdAt)}</td><td><Link className={styles.viewLink} href={`/transactions/bill-details/${item.billDetailId}`}>View</Link></td></tr>)}</tbody></table></div>}</section></TransactionShell>; }
export function BillDetailRecord({ billDetailId }: { billDetailId: string }) { const { data, error, loading, load } = useData<Detail>(`/api/bill-details/${encodeURIComponent(billDetailId)}`); if (loading) return <TransactionShell><Loading /></TransactionShell>; if (!data) return <TransactionShell><Link className={styles.backLink} href="/transactions/bill-details">← Bill Details</Link><Failure message={error} retry={load} /></TransactionShell>; const Card = ({ title, rows }: { title: string; rows: [string, string][] }) => <section className={styles.detailCard}><div className={styles.cardHeading}><h2>{title}</h2></div><div className={styles.detailItems}>{rows.map(([label, value]) => <div className={styles.detailItem} key={label}><span>{label}</span><strong>{value}</strong></div>)}</div></section>; return <TransactionShell><Link className={styles.backLink} href="/transactions/bill-details">← Bill Details</Link><header className={styles.detailHeader}><div><h1>Bill Detail #{data.billDetailId}</h1><p className={styles.detailCustomer}>{data.billNo}<span>{data.controlNo} · {data.customerName}</span></p></div><Link className={styles.secondaryButton} href={`/transactions/${encodeURIComponent(data.billNo)}`}>View Bill</Link></header><div className={styles.detailGrid}><div><Card title="Bill Information" rows={[["Bill No.", data.billNo], ["Billing Period", data.billingPeriod], ["Bill Date", date(data.billDate)], ["Status", data.billStatus || "—"]]} /><Card title="Customer Information" rows={[["Customer", data.customerName], ["Control No.", data.controlNo]]} /><Card title="Charge Information" rows={[["Charge Type", data.chargeType], ["Description", data.description || "—"], ["Quantity", data.quantity], ["Rate", money(data.rate)], ["Amount", money(data.amount)], ["Sequence No.", String(data.sequenceNo ?? "—")]]} /><Card title="Rate Information" rows={[["Rate ID", data.rateId || "—"], ["Minimum Cubic Meter", data.minimumCubicMeter || "—"], ["Maximum Cubic Meter", data.maximumCubicMeter || "Open-ended"], ["Rate Type", data.rateType || "—"], ["Effective Date", date(data.effectiveDate)], ["Expiration Date", date(data.expirationDate)]]} /></div></div></TransactionShell>; }
function Loading() { return <div className={styles.loading}><div className={styles.skeleton} style={{ height: 180 }} /></div>; }
function Failure({ message, retry }: { message: string; retry: () => void }) { return <div className={`${styles.panel} ${styles.errorState}`}><h2>Bill details unavailable</h2><p>{message}</p><button className={styles.secondaryButton} onClick={retry}>Try again</button></div>; }
