"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import type { ReferenceOption } from "@/modules/service-applications/types";
import type { ServiceAccountDetail } from "@/modules/service-accounts/types";
import { ModuleShell } from "@/modules/service-applications/ui/module-shell";
import styles from "@/modules/service-applications/ui/service-applications.module.css";

export function EditAccountForm({ controlNo }: { controlNo: string }) {
  const router = useRouter();
  const [account, setAccount] = useState<ServiceAccountDetail | null>(null);
  const [classifications, setClassifications] = useState<ReferenceOption[]>([]);
  const [connectionTypes, setConnectionTypes] = useState<ReferenceOption[]>([]);
  const [classificationCode, setClassificationCode] = useState("");
  const [connectionTypeCode, setConnectionTypeCode] = useState("");
  const [loading, setLoading] = useState(true); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState(""); const [fieldErrors, setFieldErrors] = useState<Record<string,string>>({});
  useEffect(() => { let cancelled = false; async function load() { try { const [detailResponse,optionsResponse] = await Promise.all([fetch(`/api/service-accounts/${encodeURIComponent(controlNo)}`,{cache:"no-store"}),fetch("/api/service-accounts/options")]); const [detailBody,optionsBody]=await Promise.all([detailResponse.json(),optionsResponse.json()]); if(!detailResponse.ok) throw new Error(detailBody.message); if(!optionsResponse.ok) throw new Error(optionsBody.message); if(!cancelled){setAccount(detailBody.data);setClassificationCode(detailBody.data.classificationCode);setConnectionTypeCode(detailBody.data.connectionTypeCode);setClassifications(optionsBody.data.classifications);setConnectionTypes(optionsBody.data.connectionTypes);}} catch(loadError){if(!cancelled)setError(loadError instanceof Error?loadError.message:"Unable to load the account.");} finally{if(!cancelled)setLoading(false);} } void load(); return()=>{cancelled=true;}; },[controlNo]);
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(submitting)return;const errors:Record<string,string>={};if(!classificationCode)errors.classificationCode="Select a classification.";if(!connectionTypeCode)errors.connectionTypeCode="Select a connection type.";setFieldErrors(errors);if(Object.keys(errors).length)return;setSubmitting(true);setError("");try{const response=await fetch(`/api/service-accounts/${encodeURIComponent(controlNo)}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({classificationCode,connectionTypeCode})});const body=await response.json();if(!response.ok){setFieldErrors(body.errors||{});throw new Error(body.message);}router.push(`/service-accounts/${encodeURIComponent(controlNo)}?updated=1`);}catch(submitError){setError(submitError instanceof Error?submitError.message:"Unable to update the account.");setSubmitting(false);}}
  return <ModuleShell active="service-accounts"><div className={styles.formShell}><Link className={styles.backLink} href={`/service-accounts/${encodeURIComponent(controlNo)}`}>← {controlNo}</Link><div className={styles.headingRow}><div><div className={styles.eyebrow}>Service Accounts</div><h1 className={styles.title}>Edit Service Account</h1><p className={styles.subtitle}>Update the classification or connection type.</p></div></div><form className={`${styles.panel} ${styles.formPanel}`} onSubmit={submit}>{error&&<div className={styles.notice}>{error}</div>}{loading?<div className={styles.loading}><div className={styles.skeleton} style={{height:150}}/></div>:account&&<><section className={styles.section}><h2 className={styles.sectionTitle}>{account.controlNo}</h2><p className={styles.sectionDescription}>{account.customerName} · Customer No. {account.customerNo}</p><div className={styles.fieldGrid}><div><label className={styles.label}>Classification <span className={styles.required}>*</span></label><select className={styles.select} value={classificationCode} onChange={(event)=>setClassificationCode(event.target.value)}>{classifications.map((item)=><option key={item.code} value={item.code}>{item.name}</option>)}</select>{fieldErrors.classificationCode&&<div className={styles.fieldError}>{fieldErrors.classificationCode}</div>}</div><div><label className={styles.label}>Connection Type <span className={styles.required}>*</span></label><select className={styles.select} value={connectionTypeCode} onChange={(event)=>setConnectionTypeCode(event.target.value)}>{connectionTypes.map((item)=><option key={item.code} value={item.code}>{item.name}</option>)}</select>{fieldErrors.connectionTypeCode&&<div className={styles.fieldError}>{fieldErrors.connectionTypeCode}</div>}</div><div><label className={styles.label}>Control No.</label><input className={styles.input} value={account.controlNo} disabled /></div><div><label className={styles.label}>Date Connected</label><input className={styles.input} value={account.dateConnected || "Not yet connected"} disabled /></div></div></section><div className={styles.formActions}><Link className={styles.secondaryButton} href={`/service-accounts/${encodeURIComponent(controlNo)}`}>Cancel</Link><button className={styles.button} disabled={submitting}>{submitting?"Saving…":"Save Changes"}</button></div></>}</form></div></ModuleShell>;
}
