import { db } from "@/lib/db";
import { requireAnyPermission, requirePermission } from "@/lib/permissions";
export const runtime="nodejs";
const fail=(message:string,status:number)=>Response.json({success:false,message},{status});
const id=(v:unknown)=>typeof v==="string"&&/^\d+$/.test(v)?v:"";
const amount=(v:unknown)=>{const n=typeof v==="number"?v:Number(v);return Number.isFinite(n)&&n>=0?n:null};
const listSql=`SELECT cf.connection_fee_id::text AS "connectionFeeId",cf.service_account_id::text AS "serviceAccountId",sa.control_no AS "controlNo",c.customer_name AS "customerName",cf.fee_id::text AS "feeId",f.fee_code AS "feeCode",f.fee_name AS "feeName",f.fee_type AS "feeType",cf.assessment_date::text AS "assessmentDate",cf.assessed_amount::text AS "assessedAmount",cf.amount_paid::text AS "amountPaid",cf.balance_amount::text AS "balanceAmount",cf.status,cf.bill_id::text AS "billId",b.bill_no AS "billNo",cf.remarks FROM connection_fees cf JOIN service_accounts sa ON sa.service_account_id=cf.service_account_id JOIN customers c ON c.customer_id=sa.customer_id JOIN mt_fees f ON f.fee_id=cf.fee_id LEFT JOIN bills b ON b.bill_id=cf.bill_id`;
export async function GET(request:Request){const p=new URL(request.url).searchParams;if(p.get("options")==="1"){const auth=await requireAnyPermission(["BILL_CREATE","BILL_EDIT"]);if(auth.response)return auth.response;try{const [fees,accounts]=await Promise.all([db.query(`SELECT fee_id::text AS "feeId",fee_code AS "feeCode",fee_name AS "feeName",fee_type AS "feeType",amount::text AS "defaultAmount" FROM mt_fees WHERE is_active=TRUE ORDER BY fee_code`),db.query(`SELECT sa.service_account_id::text AS "serviceAccountId",sa.control_no AS "controlNo",c.customer_name AS "customerName",sa.address,cc.classification_name AS classification,COALESCE(cs.status_name,cs.status_code,'Not set') AS "connectionStatus" FROM service_accounts sa JOIN customers c ON c.customer_id=sa.customer_id LEFT JOIN mt_customer_classification cc ON cc.classification_id=sa.classification_id LEFT JOIN mt_connection_status cs ON cs.connection_status_id=sa.connection_status_id ORDER BY sa.control_no`)]);return Response.json({success:true,data:{fees:fees.rows,accounts:accounts.rows}})}catch(e){console.error(e);return fail("Unable to load connection fee options.",500)}}const auth=await requirePermission("BILL_VIEW");if(auth.response)return auth.response;const values:unknown[]=[],where:string[]=[];const search=p.get("search")?.trim();if(search){values.push(`%${search}%`);where.push(`(sa.control_no ILIKE $${values.length} OR c.customer_name ILIKE $${values.length} OR f.fee_code ILIKE $${values.length} OR f.fee_name ILIKE $${values.length})`)}const status=p.get("status")?.trim();if(["UNPAID","PARTIAL","PAID"].includes(status||"")){values.push(status);where.push(`cf.status=$${values.length}`)}const billed=p.get("billed");if(billed==="YES")where.push("cf.bill_id IS NOT NULL");if(billed==="NO")where.push("cf.bill_id IS NULL");const sql=where.length?` WHERE ${where.join(" AND ")}`:"";try{const rows=await db.query(`${listSql}${sql} ORDER BY cf.assessment_date DESC,cf.connection_fee_id DESC`,values);return Response.json({success:true,data:rows.rows})}catch(e){console.error(e);return fail("Unable to load connection fees.",500)}}
export async function POST(request:Request){const auth=await requirePermission("BILL_CREATE");if(auth.response)return auth.response;let body:Record<string,unknown>;try{body=await request.json()}catch{return fail("Invalid request.",400)}const serviceAccountId=id(body.serviceAccountId),feeId=id(body.feeId),assessed=amount(body.assessedAmount),assessmentDate=typeof body.assessmentDate==="string"?body.assessmentDate:"",remarks=typeof body.remarks==="string"?body.remarks.trim()||null:null;if(!serviceAccountId||!feeId||assessed===null||!assessmentDate)return fail("Service account, fee, non-negative assessed amount, and assessment date are required.",400);try{const result=await db.query(`INSERT INTO connection_fees(service_account_id,fee_id,assessed_amount,amount_paid,balance_amount,assessment_date,status,remarks,created_by) SELECT $1,$2,$3,0,$3,$4::date,'UNPAID',$5,$6 WHERE EXISTS(SELECT 1 FROM service_accounts WHERE service_account_id=$1) AND EXISTS(SELECT 1 FROM mt_fees WHERE fee_id=$2 AND is_active=TRUE) RETURNING connection_fee_id::text AS "connectionFeeId"`,[serviceAccountId,feeId,assessed,assessmentDate,remarks,auth.user.userId]);if(!result.rows[0])return fail("The selected service account or active fee was not found.",400);return Response.json({success:true,data:result.rows[0]}, {status:201})}catch(e){console.error(e);return fail("Unable to create connection fee.",500)}}
