import { Pool } from "pg";
export const runtime = "nodejs";
const globalForDb = globalThis as unknown as { meterBrandsPool?: Pool };
const pool = globalForDb.meterBrandsPool ?? new Pool({ connectionString: process.env.DATABASE_URL });
if (process.env.NODE_ENV !== "production") globalForDb.meterBrandsPool = pool;
function text(value: unknown) { return typeof value === "string" ? value.trim() : ""; }
function fail(message: string, status: number) { return Response.json({ success: false, message }, { status }); }
function duplicateError(error: unknown) { return typeof error === "object" && error !== null && "code" in error && error.code === "23505"; }
function parse(body: Record<string, unknown>) { const brand = { code: text(body.brand_code).toUpperCase() || null, name: text(body.brand_name), description: text(body.description) || null, isActive: typeof body.is_active === "boolean" ? body.is_active : true }; return brand.name ? { brand } : { error: "Please complete all required fields." }; }
async function duplicate(client: Pick<Pool, "query">, brand: { code: string | null; name: string }, id?: string) { if (brand.code) { const code = await client.query(`SELECT meter_brand_id FROM mt_meter_brand WHERE brand_code = $1${id ? " AND meter_brand_id <> $2" : ""} LIMIT 1`, id ? [brand.code, id] : [brand.code]); if ((code.rowCount ?? 0) > 0) return "That brand code is already registered."; } const name = await client.query(`SELECT meter_brand_id FROM mt_meter_brand WHERE LOWER(brand_name) = LOWER($1)${id ? " AND meter_brand_id <> $2" : ""} LIMIT 1`, id ? [brand.name, id] : [brand.name]); return (name.rowCount ?? 0) > 0 ? "That meter brand name is already registered." : null; }
export async function GET() { try { const result = await pool.query(`SELECT meter_brand_id, brand_code, brand_name, description, is_active FROM mt_meter_brand ORDER BY brand_name;`); return Response.json({ success: true, data: result.rows }); } catch (error) { console.error("Failed to load meter brands:", error); return fail("Unable to load meter brands.", 500); } }
export async function POST(request: Request) { try { const parsed = parse(await request.json()); if ("error" in parsed) return fail(parsed.error, 400); const client = await pool.connect(); try { await client.query("BEGIN"); const message = await duplicate(client, parsed.brand); if (message) { await client.query("ROLLBACK"); return fail(message, 409); } const result = await client.query(`INSERT INTO mt_meter_brand (brand_code, brand_name, description, is_active) VALUES ($1, $2, $3, $4) RETURNING meter_brand_id, brand_code, brand_name, description, is_active`, [parsed.brand.code, parsed.brand.name, parsed.brand.description, parsed.brand.isActive]); await client.query("COMMIT"); return Response.json({ success: true, message: "Meter brand saved successfully.", data: result.rows[0] }, { status: 201 }); } catch (error) { await client.query("ROLLBACK"); throw error; } finally { client.release(); } } catch (error) { console.error("Failed to save meter brand:", error); return fail(duplicateError(error) ? "That brand code or meter brand name is already registered." : "The meter brand could not be saved.", duplicateError(error) ? 409 : 500); } }
export async function PUT(request: Request) { try { const body = await request.json(); const id = text(body.meter_brand_id); const parsed = parse(body); if (!/^\d+$/.test(id)) return fail("Meter brand ID is required.", 400); if ("error" in parsed) return fail(parsed.error, 400); const client = await pool.connect(); try { await client.query("BEGIN"); const existing = await client.query(`SELECT meter_brand_id FROM mt_meter_brand WHERE meter_brand_id = $1 LIMIT 1`, [id]); if ((existing.rowCount ?? 0) === 0) { await client.query("ROLLBACK"); return fail("Meter brand not found.", 404); } const message = await duplicate(client, parsed.brand, id); if (message) { await client.query("ROLLBACK"); return fail(message, 409); } const result = await client.query(`UPDATE mt_meter_brand SET brand_code = $1, brand_name = $2, description = $3, is_active = $4, updated_at = CURRENT_TIMESTAMP WHERE meter_brand_id = $5 RETURNING meter_brand_id, brand_code, brand_name, description, is_active`, [parsed.brand.code, parsed.brand.name, parsed.brand.description, parsed.brand.isActive, id]); await client.query("COMMIT"); return Response.json({ success: true, message: "Meter brand updated successfully.", data: result.rows[0] }); } catch (error) { await client.query("ROLLBACK"); throw error; } finally { client.release(); } } catch (error) { console.error("Failed to update meter brand:", error); return fail(duplicateError(error) ? "That brand code or meter brand name is already registered." : "The meter brand could not be updated.", duplicateError(error) ? 409 : 500); } }
