import { db } from "@/lib/db";
import { requirePermission } from "@/lib/permissions";
import { recalculateBill } from "@/modules/bills/server";

export const runtime = "nodejs";
type Context = { params: Promise<{ billPenaltyId: string }> };
const fail = (message: string, status: number) => Response.json({ success: false, message }, { status });

export async function GET(_: Request, { params }: Context) {
  const auth = await requirePermission("BILL_VIEW");
  if (auth.response) return auth.response;
  const id = (await params).billPenaltyId;
  if (!/^\d+$/.test(id)) return fail("Bill penalty not found.", 404);
  try { const result = await db.query(`SELECT bp.bill_penalty_id AS "billPenaltyId",bp.bill_id AS "billId",b.bill_no AS "billNo",b.bill_date::text AS "billDate",b.due_date::text AS "dueDate",b.status AS "billStatus",b.service_account_id AS "serviceAccountId",COALESCE(per.period_name,per.period_code) AS "billingPeriod",sa.control_no AS "controlNo",c.customer_name AS "customerName",pr.penalty_id AS "penaltyId",pr.penalty_code AS "penaltyCode",pr.penalty_name AS "penaltyName",pr.penalty_type AS "penaltyType",pr.description AS "penaltyDescription",bp.base_amount::text AS "baseAmount",bp.rate::text,bp.amount::text,bp.created_at::text AS "createdAt" FROM bill_penalties bp INNER JOIN bills b ON b.bill_id=bp.bill_id INNER JOIN service_accounts sa ON sa.service_account_id=b.service_account_id INNER JOIN customers c ON c.customer_id=sa.customer_id INNER JOIN mt_billing_period per ON per.billing_period_id=b.billing_period_id INNER JOIN mt_penalty_rates pr ON pr.penalty_id=bp.penalty_id WHERE bp.bill_penalty_id=$1`, [id]); if (!result.rows[0]) return fail("Bill penalty not found.", 404); return Response.json({ success: true, data: result.rows[0] }); } catch (error) { console.error("Unable to load bill penalty:", error); return fail("Unable to load bill penalty.", 500); }
}

export async function PATCH(request: Request, { params }: Context) { const auth = await requirePermission("BILL_EDIT"); if (auth.response) return auth.response; const id = (await params).billPenaltyId; let body: Record<string, unknown>; try { body = await request.json(); } catch { return fail("Invalid request.",400); } const baseAmount = typeof body.baseAmount === "string" ? body.baseAmount.trim() : ""; if (!/^\d+(\.\d{1,2})?$/.test(baseAmount) || Number(baseAmount) <= 0) return fail("Enter a base amount greater than zero.",400); const client=await db.connect(); try { await client.query("BEGIN"); const result=await client.query(`UPDATE bill_penalties bp SET base_amount=$1,amount=LEAST(($1::numeric*pr.rate/100),COALESCE(pr.maximum_penalty,($1::numeric*pr.rate/100))) FROM mt_penalty_rates pr WHERE bp.penalty_id=pr.penalty_id AND bp.bill_penalty_id=$2 RETURNING bp.bill_id::text AS "billId",bp.bill_penalty_id AS "billPenaltyId"`,[baseAmount,id]); if(!result.rows[0]) { await client.query("ROLLBACK"); return fail("Bill penalty not found.",404); } await recalculateBill(client,result.rows[0].billId,auth.user.userId); await client.query("COMMIT"); return Response.json({success:true,data:result.rows[0],message:"Penalty updated and bill recalculated."}); } catch(error) { await client.query("ROLLBACK"); console.error(error); return fail("Unable to update bill penalty.",500); } finally { client.release(); } }

export async function DELETE(_: Request, { params }: Context) { const auth = await requirePermission("BILL_EDIT"); if (auth.response) return auth.response; const id = (await params).billPenaltyId; if (!/^\d+$/.test(id)) return fail("Bill penalty not found.",404); const client=await db.connect(); try { await client.query("BEGIN"); const result=await client.query(`DELETE FROM bill_penalties WHERE bill_penalty_id=$1 RETURNING bill_id::text AS "billId"`,[id]); if(!result.rows[0]) { await client.query("ROLLBACK"); return fail("Bill penalty not found.",404); } await recalculateBill(client,result.rows[0].billId,auth.user.userId); await client.query("COMMIT"); return Response.json({success:true,message:"Penalty removed and bill recalculated."}); } catch(error) { await client.query("ROLLBACK"); console.error(error); return fail("Unable to remove bill penalty.",500); } finally { client.release(); } }
