import { db } from "@/lib/db";
import { requirePermission } from "@/lib/permissions";

export const runtime = "nodejs";
const fail=(message:string,status:number)=>Response.json({success:false,message},{status});
const text=(v:unknown,max=4000)=>typeof v==="string"?v.trim().slice(0,max):"";
const validDate=(v:string)=>/^\d{4}-\d{2}-\d{2}$/.test(v)&&!Number.isNaN(Date.parse(`${v}T00:00:00Z`));
const paidSql=`EXISTS(SELECT 1 FROM payments p JOIN mt_payment_type pt ON pt.payment_type_id=p.payment_type_id WHERE p.service_account_id=o.service_account_id AND UPPER(pt.payment_type_code)='RECONNECTION' AND UPPER(p.status)='POSTED' AND p.amount=o.fee_amount AND p.payment_date>=o.order_date)`;

export async function GET(request:Request){const auth=await requirePermission("METER_INSTALLATION_VIEW");if(auth.response)return auth.response;const q=new URL(request.url).searchParams,search=text(q.get("search"),100),status=text(q.get("status"),20).toUpperCase(),paymentStatus=text(q.get("paymentStatus"),20).toUpperCase();const values:unknown[]=[],where:string[]=[];if(["PENDING","COMPLETED","CANCELLED"].includes(status)){values.push(status);where.push(`o.status=$${values.length}`)}if(search){values.push(`%${search}%`);where.push(`(sa.control_no ILIKE $${values.length} OR c.customer_name ILIKE $${values.length})`)}if(["PAID","UNPAID"].includes(paymentStatus))where.push(paymentStatus==="PAID"?paidSql:`NOT ${paidSql}`);try{const r=await db.query(`SELECT o.reconnection_id::text AS "reconnectionId",o.service_account_id::text AS "serviceAccountId",sa.control_no AS "controlNo",c.customer_name AS "customerName",o.order_date::text AS "orderDate",o.reconnection_date::text AS "reconnectionDate",o.fee_amount::text AS "feeAmount",o.status,e.employee_name AS "performedBy",o.remarks,CASE WHEN ${paidSql} THEN 'PAID' ELSE 'UNPAID' END AS "paymentStatus" FROM reconnection_orders o JOIN service_accounts sa ON sa.service_account_id=o.service_account_id JOIN customers c ON c.customer_id=sa.customer_id LEFT JOIN mt_employee e ON e.employee_id=o.performed_by ${where.length?`WHERE ${where.join(" AND ")}`:""} ORDER BY o.order_date DESC,o.reconnection_id DESC`,values);return Response.json({success:true,data:r.rows})}catch(error){console.error("Unable to load reconnection orders:",error);return fail("Unable to load reconnection orders.",500)}}

export async function POST(request:Request){const auth=await requirePermission("METER_INSTALLATION_CREATE");if(auth.response)return auth.response;let body:Record<string,unknown>;try{body=await request.json()}catch{return fail("Invalid request.",400)}const serviceAccountId=text(body.serviceAccountId,30),orderDate=text(body.orderDate,10),remarks=text(body.remarks)||null;if(!/^\d+$/.test(serviceAccountId)||!validDate(orderDate))return fail("Complete the required reconnection order information.",400);const client=await db.connect();try{await client.query("BEGIN");const account=await client.query(`SELECT sa.service_account_id FROM service_accounts sa JOIN mt_connection_status cs ON cs.connection_status_id=sa.connection_status_id WHERE sa.service_account_id=$1 AND cs.status_code='DISCONNECTED' FOR UPDATE`,[serviceAccountId]);if(!account.rows[0])throw new Error("ACCOUNT_NOT_DISCONNECTED");const duplicate=await client.query("SELECT reconnection_id FROM reconnection_orders WHERE service_account_id=$1 AND status='PENDING'",[serviceAccountId]);if(duplicate.rows[0])throw new Error("DUPLICATE_PENDING");const fees=await client.query<{amount:string}>(`SELECT amount::text FROM mt_fees WHERE fee_type='RECONNECTION' AND is_active=TRUE AND effective_date<=$1::date AND (expiration_date IS NULL OR expiration_date>=$1::date)`,[orderDate]);if(fees.rows.length===0)throw new Error("FEE_MISSING");if(fees.rows.length>1)throw new Error("FEE_OVERLAP");const r=await client.query(`INSERT INTO reconnection_orders(service_account_id,order_date,fee_amount,status,remarks,created_by,created_at) VALUES($1,$2::date,$3,'PENDING',$4,$5,CURRENT_TIMESTAMP) RETURNING reconnection_id::text AS "reconnectionId"`,[serviceAccountId,orderDate,fees.rows[0].amount,remarks,auth.user.userId]);await client.query("COMMIT");return Response.json({success:true,data:r.rows[0]},{status:201})}catch(error){await client.query("ROLLBACK");const c=error instanceof Error?error.message:"";const m:Record<string,[string,number]>={ACCOUNT_NOT_DISCONNECTED:["Only disconnected service accounts can be reconnected.",400],DUPLICATE_PENDING:["This service account already has a pending reconnection order.",409],FEE_MISSING:["No applicable active reconnection fee is configured for this order date.",409],FEE_OVERLAP:["Multiple active reconnection fees apply to this order date. Please correct the fee configuration.",409]};if(m[c])return fail(...m[c]);console.error("Unable to create reconnection order:",error);return fail("Unable to create the reconnection order.",500)}finally{client.release()}}
