import { db } from "@/lib/db";
import { requirePermission } from "@/lib/permissions";
export const runtime="nodejs";
type Context={params:Promise<{reconnectionId:string}>};
const fail=(message:string,status:number)=>Response.json({success:false,message},{status});
const text=(v:unknown,max=4000)=>typeof v==="string"?v.trim().slice(0,max):"";
const date=(v:string)=>/^\d{4}-\d{2}-\d{2}$/.test(v)&&!Number.isNaN(Date.parse(`${v}T00:00:00Z`));
const paid=`EXISTS(SELECT 1 FROM payments p JOIN mt_payment_type pt ON pt.payment_type_id=p.payment_type_id WHERE p.service_account_id=o.service_account_id AND UPPER(pt.payment_type_code)='RECONNECTION' AND UPPER(p.status)='POSTED' AND p.amount=o.fee_amount AND p.payment_date>=o.order_date)`;
const organizationSettingKeys=["ORG_NAME","OFFICE_NAME","ORG_ADDRESS","ORG_TIN","ORG_VAT_NO","ORG_CONTACT_NO","ORG_EMAIL","ORG_WEBSITE","ORG_LOGO_PATH","REPORT_FOOTER_NOTE"];
const organizationSettingsSql=`SELECT NULLIF(BTRIM(MAX(setting_value) FILTER (WHERE setting_key='ORG_NAME')),'') AS name,NULLIF(BTRIM(MAX(setting_value) FILTER (WHERE setting_key='OFFICE_NAME')),'') AS "officeName",NULLIF(BTRIM(MAX(setting_value) FILTER (WHERE setting_key='ORG_ADDRESS')),'') AS address,NULLIF(BTRIM(MAX(setting_value) FILTER (WHERE setting_key='ORG_TIN')),'') AS tin,NULLIF(BTRIM(MAX(setting_value) FILTER (WHERE setting_key='ORG_VAT_NO')),'') AS "vatNo",NULLIF(BTRIM(MAX(setting_value) FILTER (WHERE setting_key='ORG_CONTACT_NO')),'') AS "contactNo",NULLIF(BTRIM(MAX(setting_value) FILTER (WHERE setting_key='ORG_EMAIL')),'') AS email,NULLIF(BTRIM(MAX(setting_value) FILTER (WHERE setting_key='ORG_WEBSITE')),'') AS website,NULLIF(BTRIM(MAX(setting_value) FILTER (WHERE setting_key='ORG_LOGO_PATH')),'') AS "logoPath",NULLIF(BTRIM(MAX(setting_value) FILTER (WHERE setting_key='REPORT_FOOTER_NOTE')),'') AS "footerNote" FROM public.mt_system_settings WHERE is_active=TRUE AND setting_key=ANY($1::text[])`;
export async function GET(_:Request,{params}:Context){const auth=await requirePermission("METER_INSTALLATION_VIEW");if(auth.response)return auth.response;const id=(await params).reconnectionId;if(!/^\d+$/.test(id))return fail("Reconnection order not found.",404);try{const [detail,organization]=await Promise.all([db.query(`SELECT o.reconnection_id::text AS "reconnectionId",o.service_account_id::text AS "serviceAccountId",sa.control_no AS "controlNo",c.customer_name AS "customerName",COALESCE(sa.address,c.address) AS address,cc.classification_name AS classification,COALESCE(cs.status_name,cs.status_code) AS "connectionStatus",COALESCE(m.meter_no,'-') AS "meterNo",o.order_date::text AS "orderDate",o.reconnection_date::text AS "reconnectionDate",o.fee_amount::text AS "feeAmount",CASE WHEN ${paid} THEN 'PAID' ELSE 'UNPAID' END AS "paymentStatus",o.performed_by::text AS "performedById",e.employee_name AS "performedByName",o.status,o.remarks,COALESCE(NULLIF(CONCAT_WS(' ',u.first_name,u.last_name),''),u.username,u.email) AS "createdBy",o.created_at::text AS "createdAt",o.updated_at::text AS "updatedAt" FROM reconnection_orders o JOIN service_accounts sa ON sa.service_account_id=o.service_account_id JOIN customers c ON c.customer_id=sa.customer_id LEFT JOIN mt_customer_classification cc ON cc.classification_id=sa.classification_id LEFT JOIN mt_connection_status cs ON cs.connection_status_id=sa.connection_status_id LEFT JOIN mt_employee e ON e.employee_id=o.performed_by LEFT JOIN users u ON u.user_id=o.created_by LEFT JOIN LATERAL(SELECT meter_no FROM meters WHERE service_account_id=sa.service_account_id ORDER BY meter_id DESC LIMIT 1)m ON TRUE WHERE o.reconnection_id=$1`,[id]),db.query(organizationSettingsSql,[organizationSettingKeys])]);if(!detail.rows[0])return fail("Reconnection order not found.",404);return Response.json({success:true,data:{...detail.rows[0],organization:organization.rows[0]}})}catch(error){console.error("Unable to load reconnection order:",error);return fail("Unable to load reconnection order.",500)}}
export async function PUT(request:Request,{params}:Context){const auth=await requirePermission("METER_INSTALLATION_EDIT");if(auth.response)return auth.response;const id=(await params).reconnectionId;if(!/^\d+$/.test(id))return fail("Reconnection order not found.",404);let b:Record<string,unknown>;try{b=await request.json()}catch{return fail("Invalid request.",400)}const orderDate=text(b.orderDate,10),remarks=text(b.remarks)||null;if(!date(orderDate))return fail("Enter a valid order date.",400);try{const r=await db.query(`UPDATE reconnection_orders SET order_date=$1::date,remarks=$2,updated_at=CURRENT_TIMESTAMP WHERE reconnection_id=$3 AND status='PENDING' RETURNING reconnection_id::text AS "reconnectionId"`,[orderDate,remarks,id]);if(!r.rows[0])return fail("Only pending reconnection orders can be edited.",409);return Response.json({success:true,data:r.rows[0]})}catch(error){console.error("Unable to update reconnection order:",error);return fail("Unable to update reconnection order.",500)}}
