import { db } from "@/lib/db";
import { requirePermission } from "@/lib/permissions";
export const runtime = "nodejs";
type Context = { params: Promise<{ adjustmentId: string }> };
const fail = (message: string, status: number) => Response.json({ success: false, message }, { status });
const text = (value: unknown, max = 4000) => typeof value === "string" ? value.trim().slice(0, max) : "";
function parse(body: Record<string, unknown>) { const adjustmentType = text(body.adjustmentType, 50), amount = text(body.amount, 30), reason = text(body.reason) || null, errors: Record<string, string> = {}; if (!adjustmentType) errors.adjustmentType = "Enter an adjustment type."; if (!/^-?\d+(\.\d{1,2})?$/.test(amount)) errors.amount = "Enter a valid adjustment amount."; return { adjustmentType, amount, reason, errors }; }
const detailSql = `SELECT a.adjustment_id AS "adjustmentId",a.bill_id AS "billId",b.bill_no AS "billNo",b.bill_date::text AS "billDate",b.due_date::text AS "dueDate",b.status AS "billStatus",b.service_account_id AS "serviceAccountId",COALESCE(p.period_name,p.period_code) AS "billingPeriod",sa.control_no AS "controlNo",c.customer_name AS "customerName",a.adjustment_type AS "adjustmentType",a.amount::text,a.reason,CONCAT_WS(' ',cu.first_name,cu.last_name) AS "createdBy",a.created_at::text AS "createdAt",CONCAT_WS(' ',au.first_name,au.last_name) AS "approvedBy",a.approved_at::text AS "approvedAt" FROM bill_adjustments a INNER JOIN bills b ON b.bill_id=a.bill_id INNER JOIN service_accounts sa ON sa.service_account_id=b.service_account_id INNER JOIN customers c ON c.customer_id=sa.customer_id INNER JOIN mt_billing_period p ON p.billing_period_id=b.billing_period_id LEFT JOIN users cu ON cu.user_id=a.created_by LEFT JOIN users au ON au.user_id=a.approved_by`;
export async function GET(_: Request, { params }: Context) { const auth = await requirePermission("BILL_VIEW"); if (auth.response) return auth.response; const id = (await params).adjustmentId; if (!/^\d+$/.test(id)) return fail("Bill adjustment not found.", 404); try { const result = await db.query(`${detailSql} WHERE a.adjustment_id=$1`, [id]); if (!result.rows[0]) return fail("Bill adjustment not found.", 404); return Response.json({ success: true, data: result.rows[0] }); } catch (error) { console.error(error); return fail("Unable to load bill adjustment.", 500); } }
export async function PATCH(request: Request, { params }: Context) { const auth = await requirePermission("BILL_EDIT"); if (auth.response) return auth.response; const id = (await params).adjustmentId; if (!/^\d+$/.test(id)) return fail("Bill adjustment not found.", 404); let body: Record<string, unknown>; try { body = await request.json(); } catch { return fail("Invalid request.", 400); } const value = parse(body); if (Object.keys(value.errors).length) return Response.json({ success: false, message: "Invalid adjustment data.", errors: value.errors }, { status: 400 }); try { const result = await db.query(`UPDATE bill_adjustments SET adjustment_type=$1,amount=$2,reason=$3 WHERE adjustment_id=$4 AND approved_at IS NULL RETURNING adjustment_id AS "adjustmentId"`, [value.adjustmentType, value.amount, value.reason, id]); if (!result.rows[0]) { const existing = await db.query("SELECT adjustment_id FROM bill_adjustments WHERE adjustment_id=$1", [id]); return fail(existing.rows[0] ? "Approved adjustments cannot be edited." : "Bill adjustment not found.", existing.rows[0] ? 409 : 404); } return Response.json({ success: true, data: result.rows[0], message: "Adjustment updated successfully." }); } catch (error) { console.error(error); return fail("Unable to update bill adjustment.", 500); } }

export async function DELETE(_: Request, { params }: Context) { const auth = await requirePermission("BILL_EDIT"); if (auth.response) return auth.response; const id = (await params).adjustmentId; if (!/^\d+$/.test(id)) return fail("Bill adjustment not found.", 404); const client = await db.connect(); try { await client.query("BEGIN"); const result = await client.query(`DELETE FROM bill_adjustments WHERE adjustment_id=$1 AND approved_at IS NULL RETURNING bill_id::text AS "billId"`, [id]); if (!result.rows[0]) { const existing = await client.query("SELECT adjustment_id,approved_at FROM bill_adjustments WHERE adjustment_id=$1", [id]); await client.query("ROLLBACK"); return fail(existing.rows[0]?.approved_at ? "Approved adjustments cannot be removed. Create a reversal when that workflow is available." : "Bill adjustment not found.", existing.rows[0]?.approved_at ? 409 : 404); } const { recalculateBill } = await import("@/modules/bills/server"); await recalculateBill(client, result.rows[0].billId, auth.user.userId); await client.query("COMMIT"); return Response.json({ success: true, message: "Adjustment removed successfully." }); } catch (error) { await client.query("ROLLBACK"); console.error(error); return fail("Unable to remove bill adjustment.", 500); } finally { client.release(); } }
