import { db } from "@/lib/db";
import { requirePermission } from "@/lib/permissions";

export const runtime = "nodejs";
type Context = { params: Promise<{ installationId: string }> };
const text = (value: unknown, max = 4000) => typeof value === "string" ? value.trim().slice(0, max) : "";
const fail = (message: string, status: number) => Response.json({ success: false, message }, { status });
const isDate = (value: string) => /^\d{4}-\d{2}-\d{2}$/.test(value) && !Number.isNaN(Date.parse(`${value}T00:00:00Z`));
function parse(body: Record<string, unknown>) { const value = { serviceAccountId: text(body.serviceAccountId, 30), meterId: text(body.meterId, 30), installationDate: text(body.installationDate, 10), removedDate: text(body.removedDate, 10) || null, installationType: text(body.installationType, 50) || null, reason: text(body.reason) || null, remarks: text(body.remarks) || null }; const errors: Record<string, string> = {}; if (!/^\d+$/.test(value.serviceAccountId)) errors.serviceAccountId = "Select a service account."; if (!/^\d+$/.test(value.meterId)) errors.meterId = "Select a meter."; if (!isDate(value.installationDate)) errors.installationDate = "Enter a valid installation date."; if (value.removedDate && !isDate(value.removedDate)) errors.removedDate = "Enter a valid removal date."; if (value.removedDate && isDate(value.installationDate) && value.removedDate < value.installationDate) errors.removedDate = "Removal date cannot be earlier than the installation date."; return { value, errors }; }
async function referencesExist(serviceAccountId: string, meterId: string) { const [account, meter] = await Promise.all([db.query("SELECT service_account_id FROM service_accounts WHERE service_account_id=$1", [serviceAccountId]), db.query("SELECT meter_id FROM meters WHERE meter_id=$1", [meterId])]); return Boolean(account.rows[0] && meter.rows[0]); }
function id(value: string) { return /^\d+$/.test(value) ? value : null; }

export async function GET(_: Request, { params }: Context) {
  const auth = await requirePermission("METER_INSTALLATION_VIEW"); if (auth.response) return auth.response;
  const installationId = id((await params).installationId); if (!installationId) return fail("Installation not found.", 404);
  try { const result = await db.query(`SELECT mi.installation_id AS "installationId", mi.service_account_id AS "serviceAccountId", sa.control_no AS "controlNo", c.customer_name AS "customerName", COALESCE(sa.address, c.address) AS address, mi.meter_id AS "meterId", m.meter_no AS "meterNo", ms.meter_size AS "meterSize", mt.meter_type_name AS "meterType", mb.brand_name AS "meterBrand", m.serial_no AS "serialNo", mi.installation_date::text AS "installationDate", mi.removed_date::text AS "removedDate", mi.installation_type AS "installationType", mi.reason, mi.remarks, CONCAT_WS(' ', u.first_name, u.middle_name, u.last_name) AS "performedBy", mi.created_at::text AS "createdAt" FROM meter_installations mi INNER JOIN service_accounts sa ON sa.service_account_id=mi.service_account_id INNER JOIN customers c ON c.customer_id=sa.customer_id INNER JOIN meters m ON m.meter_id=mi.meter_id INNER JOIN mt_meter_size ms ON ms.meter_size_id=m.meter_size_id LEFT JOIN mt_meter_type mt ON mt.meter_type_id=m.meter_type_id LEFT JOIN mt_meter_brand mb ON mb.meter_brand_id=m.meter_brand_id LEFT JOIN users u ON u.user_id=mi.performed_by WHERE mi.installation_id=$1`, [installationId]); if (!result.rows[0]) return fail("Installation not found.", 404); return Response.json({ success: true, data: result.rows[0] }); } catch (error) { console.error("Unable to load meter installation:", error); return fail("Unable to load meter installation.", 500); }
}

export async function PUT(request: Request, { params }: Context) {
  const auth = await requirePermission("METER_INSTALLATION_EDIT"); if (auth.response) return auth.response;
  const installationId = id((await params).installationId); if (!installationId) return fail("Installation not found.", 404);
  let body: Record<string, unknown>; try { body = await request.json(); } catch { return fail("Invalid request.", 400); }
  const { value, errors } = parse(body); if (Object.keys(errors).length) return Response.json({ success: false, message: "Please complete the required installation information.", errors }, { status: 400 });
  try { if (!(await referencesExist(value.serviceAccountId, value.meterId))) return fail("The selected service account or meter is unavailable.", 400); const result = await db.query(`UPDATE meter_installations SET service_account_id=$1, meter_id=$2, installation_date=$3::date, removed_date=$4::date, installation_type=$5, reason=$6, remarks=$7 WHERE installation_id=$8 RETURNING installation_id AS "installationId"`, [value.serviceAccountId, value.meterId, value.installationDate, value.removedDate, value.installationType, value.reason, value.remarks, installationId]); if (!result.rows[0]) return fail("Installation not found.", 404); return Response.json({ success: true, data: result.rows[0], message: "Meter installation updated successfully." }); } catch (error) { console.error("Unable to update meter installation:", error); return fail("Unable to update the meter installation.", 500); }
}
