import { db } from "@/lib/db";
import { requirePermission } from "@/lib/permissions";

export const runtime = "nodejs";
type RouteInput = { code: string; name: string; barangayId: string | null; employeeId: string | null; sequenceNo: number | null; description: string | null; isActive: boolean };
const text = (value: unknown) => typeof value === "string" ? value.trim() : "";
const fail = (message: string, status: number) => Response.json({ success: false, message }, { status });
const selectRoute = `r.route_id,r.route_code,r.route_name,r.barangay_id,b.barangay_name,r.employee_id,e.employee_name AS "employeeName",r.sequence_no,r.description,r.is_active`;
function parse(body: Record<string, unknown>): { error: string } | { route: RouteInput } { const rawSequence = body.sequence_no, barangayId = text(body.barangay_id), employeeId = text(body.employee_id), route: RouteInput = { code: text(body.route_code).toUpperCase(), name: text(body.route_name), barangayId: barangayId || null, employeeId: employeeId || null, sequenceNo: rawSequence === "" || rawSequence === null || rawSequence === undefined ? null : Number(rawSequence), description: text(body.description) || null, isActive: typeof body.is_active === "boolean" ? body.is_active : true }; if (!route.code || !route.name) return { error: "Please complete all required fields." }; if (route.barangayId && !/^\d+$/.test(route.barangayId)) return { error: "Please select a valid barangay." }; if (route.employeeId && !/^\d+$/.test(route.employeeId)) return { error: "Please select a valid meter reader." }; if (route.sequenceNo !== null && !Number.isInteger(route.sequenceNo)) return { error: "Sequence number must be a valid whole number." }; return { route }; }
async function validate(route: RouteInput, id?: string) { if (route.barangayId) { const result = await db.query("SELECT barangay_id FROM mt_barangay WHERE barangay_id=$1", [route.barangayId]); if (!result.rows[0]) return ["The selected barangay was not found.", 400] as const; } if (route.employeeId) { const result = await db.query("SELECT employee_id FROM mt_employee WHERE employee_id=$1 AND is_active=TRUE AND LOWER(TRIM(COALESCE(position,'')))='meter reader'", [route.employeeId]); if (!result.rows[0]) return ["The selected employee is not an active meter reader.", 400] as const; } const duplicate = await db.query(`SELECT route_id FROM mt_reading_route WHERE route_code=$1${id ? " AND route_id<>$2" : ""}`, id ? [route.code, id] : [route.code]); return duplicate.rows[0] ? ["That route code is already registered.", 409] as const : null; }

export async function GET() { const auth = await requirePermission("METER_READING_VIEW"); if (auth.response) return auth.response; try { const result = await db.query(`SELECT ${selectRoute} FROM mt_reading_route r LEFT JOIN mt_barangay b ON b.barangay_id=r.barangay_id LEFT JOIN mt_employee e ON e.employee_id=r.employee_id ORDER BY r.sequence_no NULLS LAST,r.route_code`); return Response.json({ success: true, data: result.rows }); } catch (error) { console.error("Failed to load reading routes:", error); return fail("Unable to load reading routes.", 500); } }
export async function POST(request: Request) { const auth = await requirePermission("METER_READING_CREATE"); if (auth.response) return auth.response; let body: Record<string, unknown>; try { body = await request.json(); } catch { return fail("Invalid request.", 400); } const parsed = parse(body); if ("error" in parsed) return fail(parsed.error, 400); const invalid = await validate(parsed.route); if (invalid) { const [message, status] = invalid; return fail(message, status); } try { const result = await db.query(`WITH inserted AS (INSERT INTO mt_reading_route(route_code,route_name,barangay_id,employee_id,sequence_no,description,is_active,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *) SELECT ${selectRoute} FROM inserted r LEFT JOIN mt_barangay b ON b.barangay_id=r.barangay_id LEFT JOIN mt_employee e ON e.employee_id=r.employee_id`, [parsed.route.code,parsed.route.name,parsed.route.barangayId,parsed.route.employeeId,parsed.route.sequenceNo,parsed.route.description,parsed.route.isActive,auth.user.userId]); return Response.json({ success: true, data: result.rows[0], message: "Reading route saved successfully." }, { status: 201 }); } catch (error) { console.error("Failed to save reading route:", error); return fail(typeof error === "object" && error && "code" in error && error.code === "23505" ? "That route code is already registered." : "The reading route could not be saved.", typeof error === "object" && error && "code" in error && error.code === "23505" ? 409 : 500); } }
export async function PUT(request: Request) { const auth = await requirePermission("METER_READING_EDIT"); if (auth.response) return auth.response; let body: Record<string, unknown>; try { body = await request.json(); } catch { return fail("Invalid request.", 400); } const id = text(body.route_id), parsed = parse(body); if (!/^\d+$/.test(id)) return fail("Reading route ID is required.", 400); if ("error" in parsed) return fail(parsed.error, 400); const invalid = await validate(parsed.route, id); if (invalid) { const [message, status] = invalid; return fail(message, status); } try { const result = await db.query(`WITH updated AS (UPDATE mt_reading_route SET route_code=$1,route_name=$2,barangay_id=$3,employee_id=$4,sequence_no=$5,description=$6,is_active=$7,updated_by=$8,updated_at=NOW() WHERE route_id=$9 RETURNING *) SELECT ${selectRoute} FROM updated r LEFT JOIN mt_barangay b ON b.barangay_id=r.barangay_id LEFT JOIN mt_employee e ON e.employee_id=r.employee_id`, [parsed.route.code,parsed.route.name,parsed.route.barangayId,parsed.route.employeeId,parsed.route.sequenceNo,parsed.route.description,parsed.route.isActive,auth.user.userId,id]); if (!result.rows[0]) return fail("Reading route record was not found.", 404); return Response.json({ success: true, data: result.rows[0], message: "Reading route updated successfully." }); } catch (error) { console.error("Failed to update reading route:", error); return fail(typeof error === "object" && error && "code" in error && error.code === "23505" ? "That route code is already registered." : "The reading route could not be updated.", typeof error === "object" && error && "code" in error && error.code === "23505" ? 409 : 500); } }
