import { db } from "@/lib/db";
import { requirePermission } from "@/lib/permissions";
import { failure, parseBill, total } from "@/modules/bills/server";
export const runtime = "nodejs";
type Context = { params: Promise<{ billNo: string }> };
const fail = (message: string, status: number) => Response.json({ success: false, message }, { status });
const detailSql = `SELECT b.bill_id AS "billId",b.bill_no AS "billNo",b.service_account_id AS "serviceAccountId",sa.control_no AS "controlNo",c.customer_name AS "customerName",st.service_type_name AS "serviceType",b.billing_period_id AS "billingPeriodId",bp.period_code AS "periodCode",COALESCE(bp.period_name,bp.period_code) AS "billingPeriod",bp.status AS "billingPeriodStatus",b.reading_id AS "readingId",rd.reading_date::text AS "readingDate",rd.previous_reading::text AS "previousReading",rd.present_reading::text AS "presentReading",rd.consumption::text AS consumption,m.meter_no AS "meterNo",b.bill_date::text AS "billDate",b.due_date::text AS "dueDate",b.water_consumption_amount::text AS "waterConsumptionAmount",b.previous_balance::text AS "previousBalance",b.penalty_amount::text AS "penaltyAmount",b.connection_fee_amount::text AS "connectionFeeAmount",b.adjustment_amount::text AS "adjustmentAmount",b.total_amount_due::text AS "totalAmountDue",b.status,b.remarks,b.created_at::text AS "createdAt",b.updated_at::text AS "updatedAt" FROM bills b JOIN service_accounts sa ON sa.service_account_id=b.service_account_id JOIN customers c ON c.customer_id=sa.customer_id JOIN mt_billing_period bp ON bp.billing_period_id=b.billing_period_id LEFT JOIN mt_service_type st ON st.service_type_id=sa.service_type_id LEFT JOIN meter_readings rd ON rd.reading_id=b.reading_id LEFT JOIN meters m ON m.meter_id=rd.meter_id`;
export async function GET(_: Request, { params }: Context) { const auth = await requirePermission("BILL_VIEW"); if (auth.response) return auth.response; const billNo = decodeURIComponent((await params).billNo); if (!billNo || billNo.length > 50) return fail("Bill not found.", 404); try { const result = await db.query(`${detailSql} WHERE b.bill_no=$1`, [billNo]); if (!result.rows[0]) return fail("Bill not found.", 404); return Response.json({ success: true, data: result.rows[0] }); } catch (error) { console.error("Unable to load bill:", error); return fail("Unable to load bill.", 500); } }
export async function PATCH(request: Request, { params }: Context) { const auth = await requirePermission("BILL_EDIT"); if (auth.response) return auth.response; const billNo = decodeURIComponent((await params).billNo); let body: Record<string, unknown>; try { body = await request.json(); } catch { return fail("Invalid request.", 400); } const { value, errors } = parseBill(body, true); if (Object.keys(errors).length) return Response.json({ success: false, message: "Invalid bill data.", errors }, { status: 400 }); try { const result = await db.query(`UPDATE bills SET bill_date=$1::date,due_date=$2::date,water_consumption_amount=$3,previous_balance=$4,penalty_amount=$5,connection_fee_amount=$6,adjustment_amount=$7,total_amount_due=$8,status=$9,remarks=$10,updated_by=$11,updated_at=NOW() WHERE bill_no=$12 RETURNING bill_id AS "billId",bill_no AS "billNo"`, [value.billDate, value.dueDate, value.waterConsumptionAmount, value.previousBalance, value.penaltyAmount, value.connectionFeeAmount, value.adjustmentAmount, total(value), value.status, value.remarks, auth.user.userId, billNo]); if (!result.rows[0]) return fail("Bill not found.", 404); return Response.json({ success: true, data: result.rows[0], message: "Bill updated successfully." }); } catch (error) { const known = failure(error); if (known) return fail(...known); console.error("Unable to update bill:", error); return fail("Unable to update bill.", 500); } }
