import { Pool } from "pg";
export const runtime = "nodejs";
const globalForDb = globalThis as unknown as { readingStatusesPool?: Pool };
const pool = globalForDb.readingStatusesPool ?? new Pool({ connectionString: process.env.DATABASE_URL });
if (process.env.NODE_ENV !== "production") globalForDb.readingStatusesPool = pool;
function text(value: unknown) { return typeof value === "string" ? value.trim() : ""; }
function fail(message: string, status: number) { return Response.json({ success: false, message }, { status }); }
function duplicateError(error: unknown) { return typeof error === "object" && error !== null && "code" in error && error.code === "23505"; }
function parse(body: Record<string, unknown>) { const value = { code: text(body.status_code).toUpperCase(), name: text(body.status_name), description: text(body.description) || null, isActive: typeof body.is_active === "boolean" ? body.is_active : true }; return value.code && value.name ? { value } : { error: "Please complete all required fields." }; }
export async function GET() { try { const result = await pool.query(`SELECT reading_status_id, status_code, status_name, description, is_active FROM mt_reading_status ORDER BY status_code;`); return Response.json({ success: true, data: result.rows }); } catch (error) { console.error("Failed to load reading statuses:", error); return fail("Unable to load reading statuses.", 500); } }
export async function POST(request: Request) { try { const parsed = parse(await request.json()); if ("error" in parsed) return fail(parsed.error, 400); const client = await pool.connect(); try { await client.query("BEGIN"); const duplicate = await client.query(`SELECT reading_status_id FROM mt_reading_status WHERE status_code = $1 LIMIT 1`, [parsed.value.code]); if ((duplicate.rowCount ?? 0) > 0) { await client.query("ROLLBACK"); return fail("That reading status code is already registered.", 409); } const result = await client.query(`INSERT INTO mt_reading_status (status_code, status_name, description, is_active) VALUES ($1, $2, $3, $4) RETURNING reading_status_id, status_code, status_name, description, is_active`, [parsed.value.code, parsed.value.name, parsed.value.description, parsed.value.isActive]); await client.query("COMMIT"); return Response.json({ success: true, message: "Reading status saved successfully.", data: result.rows[0] }, { status: 201 }); } catch (error) { await client.query("ROLLBACK"); throw error; } finally { client.release(); } } catch (error) { console.error("Failed to save reading status:", error); return fail(duplicateError(error) ? "That reading status code is already registered." : "The reading status could not be saved.", duplicateError(error) ? 409 : 500); } }
export async function PUT(request: Request) { try { const body = await request.json(); const id = text(body.reading_status_id); const parsed = parse(body); if (!/^\d+$/.test(id)) return fail("Reading status ID is required.", 400); if ("error" in parsed) return fail(parsed.error, 400); const client = await pool.connect(); try { await client.query("BEGIN"); const existing = await client.query(`SELECT reading_status_id FROM mt_reading_status WHERE reading_status_id = $1 LIMIT 1`, [id]); if ((existing.rowCount ?? 0) === 0) { await client.query("ROLLBACK"); return fail("Reading status not found.", 404); } const duplicate = await client.query(`SELECT reading_status_id FROM mt_reading_status WHERE status_code = $1 AND reading_status_id <> $2 LIMIT 1`, [parsed.value.code, id]); if ((duplicate.rowCount ?? 0) > 0) { await client.query("ROLLBACK"); return fail("That reading status code is already registered.", 409); } const result = await client.query(`UPDATE mt_reading_status SET status_code = $1, status_name = $2, description = $3, is_active = $4, updated_at = CURRENT_TIMESTAMP WHERE reading_status_id = $5 RETURNING reading_status_id, status_code, status_name, description, is_active`, [parsed.value.code, parsed.value.name, parsed.value.description, parsed.value.isActive, id]); await client.query("COMMIT"); return Response.json({ success: true, message: "Reading status updated successfully.", data: result.rows[0] }); } catch (error) { await client.query("ROLLBACK"); throw error; } finally { client.release(); } } catch (error) { console.error("Failed to update reading status:", error); return fail(duplicateError(error) ? "That reading status code is already registered." : "The reading status could not be updated.", duplicateError(error) ? 409 : 500); } }
